import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 1 to 106, whose indices in `theConfigs` range over
the segment `[0, 106)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job001to106.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 1 passes the reducibility check. -/
theorem red_cf001 : checkReducible cf001 = true := by decide +kernel

/-- Configuration 2 passes the reducibility check. -/
theorem red_cf002 : checkReducible cf002 = true := by decide +kernel

/-- Configuration 3 passes the reducibility check. -/
theorem red_cf003 : checkReducible cf003 = true := by decide +kernel

/-- Configuration 4 passes the reducibility check. -/
theorem red_cf004 : checkReducible cf004 = true := by decide +kernel

/-- Configuration 5 passes the reducibility check. -/
theorem red_cf005 : checkReducible cf005 = true := by decide +kernel

/-- Configuration 6 passes the reducibility check. -/
theorem red_cf006 : checkReducible cf006 = true := by decide +kernel

/-- Configuration 7 passes the reducibility check. -/
theorem red_cf007 : checkReducible cf007 = true := by decide +kernel

/-- Configuration 8 passes the reducibility check. -/
theorem red_cf008 : checkReducible cf008 = true := by decide +kernel

/-- Configuration 9 passes the reducibility check. -/
theorem red_cf009 : checkReducible cf009 = true := by decide +kernel

/-- Configuration 10 passes the reducibility check. -/
theorem red_cf010 : checkReducible cf010 = true := by decide +kernel

/-- Configuration 11 passes the reducibility check. -/
theorem red_cf011 : checkReducible cf011 = true := by decide +kernel

/-- Configuration 12 passes the reducibility check. -/
theorem red_cf012 : checkReducible cf012 = true := by decide +kernel

/-- Configuration 13 passes the reducibility check. -/
theorem red_cf013 : checkReducible cf013 = true := by decide +kernel

/-- Configuration 14 passes the reducibility check. -/
theorem red_cf014 : checkReducible cf014 = true := by decide +kernel

/-- Configuration 15 passes the reducibility check. -/
theorem red_cf015 : checkReducible cf015 = true := by decide +kernel

/-- Configuration 16 passes the reducibility check. -/
theorem red_cf016 : checkReducible cf016 = true := by decide +kernel

/-- Configuration 17 passes the reducibility check. -/
theorem red_cf017 : checkReducible cf017 = true := by decide +kernel

/-- Configuration 18 passes the reducibility check. -/
theorem red_cf018 : checkReducible cf018 = true := by decide +kernel

/-- Configuration 19 passes the reducibility check. -/
theorem red_cf019 : checkReducible cf019 = true := by decide +kernel

/-- Configuration 20 passes the reducibility check. -/
theorem red_cf020 : checkReducible cf020 = true := by decide +kernel

/-- Configuration 21 passes the reducibility check. -/
theorem red_cf021 : checkReducible cf021 = true := by decide +kernel

/-- Configuration 22 passes the reducibility check. -/
theorem red_cf022 : checkReducible cf022 = true := by decide +kernel

/-- Configuration 23 passes the reducibility check. -/
theorem red_cf023 : checkReducible cf023 = true := by decide +kernel

/-- Configuration 24 passes the reducibility check. -/
theorem red_cf024 : checkReducible cf024 = true := by decide +kernel

/-- Configuration 25 passes the reducibility check. -/
theorem red_cf025 : checkReducible cf025 = true := by decide +kernel

/-- Configuration 26 passes the reducibility check. -/
theorem red_cf026 : checkReducible cf026 = true := by decide +kernel

/-- Configuration 27 passes the reducibility check. -/
theorem red_cf027 : checkReducible cf027 = true := by decide +kernel

/-- Configuration 28 passes the reducibility check. -/
theorem red_cf028 : checkReducible cf028 = true := by decide +kernel

/-- Configuration 29 passes the reducibility check. -/
theorem red_cf029 : checkReducible cf029 = true := by decide +kernel

/-- Configuration 30 passes the reducibility check. -/
theorem red_cf030 : checkReducible cf030 = true := by decide +kernel

/-- Configuration 31 passes the reducibility check. -/
theorem red_cf031 : checkReducible cf031 = true := by decide +kernel

/-- Configuration 32 passes the reducibility check. -/
theorem red_cf032 : checkReducible cf032 = true := by decide +kernel

/-- Configuration 33 passes the reducibility check. -/
theorem red_cf033 : checkReducible cf033 = true := by decide +kernel

/-- Configuration 34 passes the reducibility check. -/
theorem red_cf034 : checkReducible cf034 = true := by decide +kernel

/-- Configuration 35 passes the reducibility check. -/
theorem red_cf035 : checkReducible cf035 = true := by decide +kernel

/-- Configuration 36 passes the reducibility check. -/
theorem red_cf036 : checkReducible cf036 = true := by decide +kernel

/-- Configuration 37 passes the reducibility check. -/
theorem red_cf037 : checkReducible cf037 = true := by decide +kernel

/-- Configuration 38 passes the reducibility check. -/
theorem red_cf038 : checkReducible cf038 = true := by decide +kernel

/-- Configuration 39 passes the reducibility check. -/
theorem red_cf039 : checkReducible cf039 = true := by decide +kernel

/-- Configuration 40 passes the reducibility check. -/
theorem red_cf040 : checkReducible cf040 = true := by decide +kernel

/-- Configuration 41 passes the reducibility check. -/
theorem red_cf041 : checkReducible cf041 = true := by decide +kernel

/-- Configuration 42 passes the reducibility check. -/
theorem red_cf042 : checkReducible cf042 = true := by decide +kernel

/-- Configuration 43 passes the reducibility check. -/
theorem red_cf043 : checkReducible cf043 = true := by decide +kernel

/-- Configuration 44 passes the reducibility check. -/
theorem red_cf044 : checkReducible cf044 = true := by decide +kernel

/-- Configuration 45 passes the reducibility check. -/
theorem red_cf045 : checkReducible cf045 = true := by decide +kernel

/-- Configuration 46 passes the reducibility check. -/
theorem red_cf046 : checkReducible cf046 = true := by decide +kernel

/-- Configuration 47 passes the reducibility check. -/
theorem red_cf047 : checkReducible cf047 = true := by decide +kernel

/-- Configuration 48 passes the reducibility check. -/
theorem red_cf048 : checkReducible cf048 = true := by decide +kernel

/-- Configuration 49 passes the reducibility check. -/
theorem red_cf049 : checkReducible cf049 = true := by decide +kernel

/-- Configuration 50 passes the reducibility check. -/
theorem red_cf050 : checkReducible cf050 = true := by decide +kernel

/-- Configuration 51 passes the reducibility check. -/
theorem red_cf051 : checkReducible cf051 = true := by decide +kernel

/-- Configuration 52 passes the reducibility check. -/
theorem red_cf052 : checkReducible cf052 = true := by decide +kernel

/-- Configuration 53 passes the reducibility check. -/
theorem red_cf053 : checkReducible cf053 = true := by decide +kernel

/-- Configuration 54 passes the reducibility check. -/
theorem red_cf054 : checkReducible cf054 = true := by decide +kernel

/-- Configuration 55 passes the reducibility check. -/
theorem red_cf055 : checkReducible cf055 = true := by decide +kernel

/-- Configuration 56 passes the reducibility check. -/
theorem red_cf056 : checkReducible cf056 = true := by decide +kernel

/-- Configuration 57 passes the reducibility check. -/
theorem red_cf057 : checkReducible cf057 = true := by decide +kernel

/-- Configuration 58 passes the reducibility check. -/
theorem red_cf058 : checkReducible cf058 = true := by decide +kernel

/-- Configuration 59 passes the reducibility check. -/
theorem red_cf059 : checkReducible cf059 = true := by decide +kernel

/-- Configuration 60 passes the reducibility check. -/
theorem red_cf060 : checkReducible cf060 = true := by decide +kernel

/-- Configuration 61 passes the reducibility check. -/
theorem red_cf061 : checkReducible cf061 = true := by decide +kernel

/-- Configuration 62 passes the reducibility check. -/
theorem red_cf062 : checkReducible cf062 = true := by decide +kernel

/-- Configuration 63 passes the reducibility check. -/
theorem red_cf063 : checkReducible cf063 = true := by decide +kernel

/-- Configuration 64 passes the reducibility check. -/
theorem red_cf064 : checkReducible cf064 = true := by decide +kernel

/-- Configuration 65 passes the reducibility check. -/
theorem red_cf065 : checkReducible cf065 = true := by decide +kernel

/-- Configuration 66 passes the reducibility check. -/
theorem red_cf066 : checkReducible cf066 = true := by decide +kernel

/-- Configuration 67 passes the reducibility check. -/
theorem red_cf067 : checkReducible cf067 = true := by decide +kernel

/-- Configuration 68 passes the reducibility check. -/
theorem red_cf068 : checkReducible cf068 = true := by decide +kernel

/-- Configuration 69 passes the reducibility check. -/
theorem red_cf069 : checkReducible cf069 = true := by decide +kernel

/-- Configuration 70 passes the reducibility check. -/
theorem red_cf070 : checkReducible cf070 = true := by decide +kernel

/-- Configuration 71 passes the reducibility check. -/
theorem red_cf071 : checkReducible cf071 = true := by decide +kernel

/-- Configuration 72 passes the reducibility check. -/
theorem red_cf072 : checkReducible cf072 = true := by decide +kernel

/-- Configuration 73 passes the reducibility check. -/
theorem red_cf073 : checkReducible cf073 = true := by decide +kernel

/-- Configuration 74 passes the reducibility check. -/
theorem red_cf074 : checkReducible cf074 = true := by decide +kernel

/-- Configuration 75 passes the reducibility check. -/
theorem red_cf075 : checkReducible cf075 = true := by decide +kernel

/-- Configuration 76 passes the reducibility check. -/
theorem red_cf076 : checkReducible cf076 = true := by decide +kernel

/-- Configuration 77 passes the reducibility check. -/
theorem red_cf077 : checkReducible cf077 = true := by decide +kernel

/-- Configuration 78 passes the reducibility check. -/
theorem red_cf078 : checkReducible cf078 = true := by decide +kernel

/-- Configuration 79 passes the reducibility check. -/
theorem red_cf079 : checkReducible cf079 = true := by decide +kernel

/-- Configuration 80 passes the reducibility check. -/
theorem red_cf080 : checkReducible cf080 = true := by decide +kernel

/-- Configuration 81 passes the reducibility check. -/
theorem red_cf081 : checkReducible cf081 = true := by decide +kernel

/-- Configuration 82 passes the reducibility check. -/
theorem red_cf082 : checkReducible cf082 = true := by decide +kernel

/-- Configuration 83 passes the reducibility check. -/
theorem red_cf083 : checkReducible cf083 = true := by decide +kernel

/-- Configuration 84 passes the reducibility check. -/
theorem red_cf084 : checkReducible cf084 = true := by decide +kernel

/-- Configuration 85 passes the reducibility check. -/
theorem red_cf085 : checkReducible cf085 = true := by decide +kernel

/-- Configuration 86 passes the reducibility check. -/
theorem red_cf086 : checkReducible cf086 = true := by decide +kernel

/-- Configuration 87 passes the reducibility check. -/
theorem red_cf087 : checkReducible cf087 = true := by decide +kernel

/-- Configuration 88 passes the reducibility check. -/
theorem red_cf088 : checkReducible cf088 = true := by decide +kernel

/-- Configuration 89 passes the reducibility check. -/
theorem red_cf089 : checkReducible cf089 = true := by decide +kernel

/-- Configuration 90 passes the reducibility check. -/
theorem red_cf090 : checkReducible cf090 = true := by decide +kernel

/-- Configuration 91 passes the reducibility check. -/
theorem red_cf091 : checkReducible cf091 = true := by decide +kernel

/-- Configuration 92 passes the reducibility check. -/
theorem red_cf092 : checkReducible cf092 = true := by decide +kernel

/-- Configuration 93 passes the reducibility check. -/
theorem red_cf093 : checkReducible cf093 = true := by decide +kernel

/-- Configuration 94 passes the reducibility check. -/
theorem red_cf094 : checkReducible cf094 = true := by decide +kernel

/-- Configuration 95 passes the reducibility check. -/
theorem red_cf095 : checkReducible cf095 = true := by decide +kernel

/-- Configuration 96 passes the reducibility check. -/
theorem red_cf096 : checkReducible cf096 = true := by decide +kernel

/-- Configuration 97 passes the reducibility check. -/
theorem red_cf097 : checkReducible cf097 = true := by decide +kernel

/-- Configuration 98 passes the reducibility check. -/
theorem red_cf098 : checkReducible cf098 = true := by decide +kernel

/-- Configuration 99 passes the reducibility check. -/
theorem red_cf099 : checkReducible cf099 = true := by decide +kernel

/-- Configuration 100 passes the reducibility check. -/
theorem red_cf100 : checkReducible cf100 = true := by decide +kernel

/-- Configuration 101 passes the reducibility check. -/
theorem red_cf101 : checkReducible cf101 = true := by decide +kernel

/-- Configuration 102 passes the reducibility check. -/
theorem red_cf102 : checkReducible cf102 = true := by decide +kernel

/-- Configuration 103 passes the reducibility check. -/
theorem red_cf103 : checkReducible cf103 = true := by decide +kernel

/-- Configuration 104 passes the reducibility check. -/
theorem red_cf104 : checkReducible cf104 = true := by decide +kernel

/-- Configuration 105 passes the reducibility check. -/
theorem red_cf105 : checkReducible cf105 = true := by decide +kernel

/-- Configuration 106 passes the reducibility check. -/
theorem red_cf106 : checkReducible cf106 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 1 to 106 are reducible. -/
theorem red000to106 : ReducibleInRange 0 106 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf001
    | 1 => Or.inr red_cf002
    | 2 => Or.inr red_cf003
    | 3 => Or.inr red_cf004
    | 4 => Or.inr red_cf005
    | 5 => Or.inr red_cf006
    | 6 => Or.inr red_cf007
    | 7 => Or.inr red_cf008
    | 8 => Or.inr red_cf009
    | 9 => Or.inr red_cf010
    | 10 => Or.inr red_cf011
    | 11 => Or.inr red_cf012
    | 12 => Or.inr red_cf013
    | 13 => Or.inr red_cf014
    | 14 => Or.inr red_cf015
    | 15 => Or.inr red_cf016
    | 16 => Or.inr red_cf017
    | 17 => Or.inr red_cf018
    | 18 => Or.inr red_cf019
    | 19 => Or.inr red_cf020
    | 20 => Or.inr red_cf021
    | 21 => Or.inr red_cf022
    | 22 => Or.inr red_cf023
    | 23 => Or.inr red_cf024
    | 24 => Or.inr red_cf025
    | 25 => Or.inr red_cf026
    | 26 => Or.inr red_cf027
    | 27 => Or.inr red_cf028
    | 28 => Or.inr red_cf029
    | 29 => Or.inr red_cf030
    | 30 => Or.inr red_cf031
    | 31 => Or.inr red_cf032
    | 32 => Or.inr red_cf033
    | 33 => Or.inr red_cf034
    | 34 => Or.inr red_cf035
    | 35 => Or.inr red_cf036
    | 36 => Or.inr red_cf037
    | 37 => Or.inr red_cf038
    | 38 => Or.inr red_cf039
    | 39 => Or.inr red_cf040
    | 40 => Or.inr red_cf041
    | 41 => Or.inr red_cf042
    | 42 => Or.inr red_cf043
    | 43 => Or.inr red_cf044
    | 44 => Or.inr red_cf045
    | 45 => Or.inr red_cf046
    | 46 => Or.inr red_cf047
    | 47 => Or.inr red_cf048
    | 48 => Or.inr red_cf049
    | 49 => Or.inr red_cf050
    | 50 => Or.inr red_cf051
    | 51 => Or.inr red_cf052
    | 52 => Or.inr red_cf053
    | 53 => Or.inr red_cf054
    | 54 => Or.inr red_cf055
    | 55 => Or.inr red_cf056
    | 56 => Or.inr red_cf057
    | 57 => Or.inr red_cf058
    | 58 => Or.inr red_cf059
    | 59 => Or.inr red_cf060
    | 60 => Or.inr red_cf061
    | 61 => Or.inr red_cf062
    | 62 => Or.inr red_cf063
    | 63 => Or.inr red_cf064
    | 64 => Or.inr red_cf065
    | 65 => Or.inr red_cf066
    | 66 => Or.inr red_cf067
    | 67 => Or.inr red_cf068
    | 68 => Or.inr red_cf069
    | 69 => Or.inr red_cf070
    | 70 => Or.inr red_cf071
    | 71 => Or.inr red_cf072
    | 72 => Or.inr red_cf073
    | 73 => Or.inr red_cf074
    | 74 => Or.inr red_cf075
    | 75 => Or.inr red_cf076
    | 76 => Or.inr red_cf077
    | 77 => Or.inr red_cf078
    | 78 => Or.inr red_cf079
    | 79 => Or.inr red_cf080
    | 80 => Or.inr red_cf081
    | 81 => Or.inr red_cf082
    | 82 => Or.inr red_cf083
    | 83 => Or.inr red_cf084
    | 84 => Or.inr red_cf085
    | 85 => Or.inr red_cf086
    | 86 => Or.inr red_cf087
    | 87 => Or.inr red_cf088
    | 88 => Or.inr red_cf089
    | 89 => Or.inr red_cf090
    | 90 => Or.inr red_cf091
    | 91 => Or.inr red_cf092
    | 92 => Or.inr red_cf093
    | 93 => Or.inr red_cf094
    | 94 => Or.inr red_cf095
    | 95 => Or.inr red_cf096
    | 96 => Or.inr red_cf097
    | 97 => Or.inr red_cf098
    | 98 => Or.inr red_cf099
    | 99 => Or.inr red_cf100
    | 100 => Or.inr red_cf101
    | 101 => Or.inr red_cf102
    | 102 => Or.inr red_cf103
    | 103 => Or.inr red_cf104
    | 104 => Or.inr red_cf105
    | 105 => Or.inr red_cf106
    | n + 106 => Or.inl (Nat.le_add_left 106 n)

end FourColor
