import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 190 to 206, whose indices in `theConfigs` range over
the segment `[189, 206)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job190to206.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 190 passes the reducibility check. -/
theorem red_cf190 : checkReducible cf190 = true := by decide +kernel

/-- Configuration 191 passes the reducibility check. -/
theorem red_cf191 : checkReducible cf191 = true := by decide +kernel

/-- Configuration 192 passes the reducibility check. -/
theorem red_cf192 : checkReducible cf192 = true := by decide +kernel

/-- Configuration 193 passes the reducibility check. -/
theorem red_cf193 : checkReducible cf193 = true := by decide +kernel

/-- Configuration 194 passes the reducibility check. -/
theorem red_cf194 : checkReducible cf194 = true := by decide +kernel

/-- Configuration 195 passes the reducibility check. -/
theorem red_cf195 : checkReducible cf195 = true := by decide +kernel

/-- Configuration 196 passes the reducibility check. -/
theorem red_cf196 : checkReducible cf196 = true := by decide +kernel

/-- Configuration 197 passes the reducibility check. -/
theorem red_cf197 : checkReducible cf197 = true := by decide +kernel

/-- Configuration 198 passes the reducibility check. -/
theorem red_cf198 : checkReducible cf198 = true := by decide +kernel

/-- Configuration 199 passes the reducibility check. -/
theorem red_cf199 : checkReducible cf199 = true := by decide +kernel

/-- Configuration 200 passes the reducibility check. -/
theorem red_cf200 : checkReducible cf200 = true := by decide +kernel

/-- Configuration 201 passes the reducibility check. -/
theorem red_cf201 : checkReducible cf201 = true := by decide +kernel

/-- Configuration 202 passes the reducibility check. -/
theorem red_cf202 : checkReducible cf202 = true := by decide +kernel

/-- Configuration 203 passes the reducibility check. -/
theorem red_cf203 : checkReducible cf203 = true := by decide +kernel

/-- Configuration 204 passes the reducibility check. -/
theorem red_cf204 : checkReducible cf204 = true := by decide +kernel

/-- Configuration 205 passes the reducibility check. -/
theorem red_cf205 : checkReducible cf205 = true := by decide +kernel

/-- Configuration 206 passes the reducibility check. -/
theorem red_cf206 : checkReducible cf206 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 190 to 206 are reducible. -/
theorem red189to206 : ReducibleInRange 189 206 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf190
    | 1 => Or.inr red_cf191
    | 2 => Or.inr red_cf192
    | 3 => Or.inr red_cf193
    | 4 => Or.inr red_cf194
    | 5 => Or.inr red_cf195
    | 6 => Or.inr red_cf196
    | 7 => Or.inr red_cf197
    | 8 => Or.inr red_cf198
    | 9 => Or.inr red_cf199
    | 10 => Or.inr red_cf200
    | 11 => Or.inr red_cf201
    | 12 => Or.inr red_cf202
    | 13 => Or.inr red_cf203
    | 14 => Or.inr red_cf204
    | 15 => Or.inr red_cf205
    | 16 => Or.inr red_cf206
    | n + 17 => Or.inl (Nat.le_add_left 17 n)

end FourColor
