import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 107 to 164, whose indices in `theConfigs` range over
the segment `[106, 164)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job107to164.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 107 passes the reducibility check. -/
theorem red_cf107 : checkReducible cf107 = true := by decide +kernel

/-- Configuration 108 passes the reducibility check. -/
theorem red_cf108 : checkReducible cf108 = true := by decide +kernel

/-- Configuration 109 passes the reducibility check. -/
theorem red_cf109 : checkReducible cf109 = true := by decide +kernel

/-- Configuration 110 passes the reducibility check. -/
theorem red_cf110 : checkReducible cf110 = true := by decide +kernel

/-- Configuration 111 passes the reducibility check. -/
theorem red_cf111 : checkReducible cf111 = true := by decide +kernel

/-- Configuration 112 passes the reducibility check. -/
theorem red_cf112 : checkReducible cf112 = true := by decide +kernel

/-- Configuration 113 passes the reducibility check. -/
theorem red_cf113 : checkReducible cf113 = true := by decide +kernel

/-- Configuration 114 passes the reducibility check. -/
theorem red_cf114 : checkReducible cf114 = true := by decide +kernel

/-- Configuration 115 passes the reducibility check. -/
theorem red_cf115 : checkReducible cf115 = true := by decide +kernel

/-- Configuration 116 passes the reducibility check. -/
theorem red_cf116 : checkReducible cf116 = true := by decide +kernel

/-- Configuration 117 passes the reducibility check. -/
theorem red_cf117 : checkReducible cf117 = true := by decide +kernel

/-- Configuration 118 passes the reducibility check. -/
theorem red_cf118 : checkReducible cf118 = true := by decide +kernel

/-- Configuration 119 passes the reducibility check. -/
theorem red_cf119 : checkReducible cf119 = true := by decide +kernel

/-- Configuration 120 passes the reducibility check. -/
theorem red_cf120 : checkReducible cf120 = true := by decide +kernel

/-- Configuration 121 passes the reducibility check. -/
theorem red_cf121 : checkReducible cf121 = true := by decide +kernel

/-- Configuration 122 passes the reducibility check. -/
theorem red_cf122 : checkReducible cf122 = true := by decide +kernel

/-- Configuration 123 passes the reducibility check. -/
theorem red_cf123 : checkReducible cf123 = true := by decide +kernel

/-- Configuration 124 passes the reducibility check. -/
theorem red_cf124 : checkReducible cf124 = true := by decide +kernel

/-- Configuration 125 passes the reducibility check. -/
theorem red_cf125 : checkReducible cf125 = true := by decide +kernel

/-- Configuration 126 passes the reducibility check. -/
theorem red_cf126 : checkReducible cf126 = true := by decide +kernel

/-- Configuration 127 passes the reducibility check. -/
theorem red_cf127 : checkReducible cf127 = true := by decide +kernel

/-- Configuration 128 passes the reducibility check. -/
theorem red_cf128 : checkReducible cf128 = true := by decide +kernel

/-- Configuration 129 passes the reducibility check. -/
theorem red_cf129 : checkReducible cf129 = true := by decide +kernel

/-- Configuration 130 passes the reducibility check. -/
theorem red_cf130 : checkReducible cf130 = true := by decide +kernel

/-- Configuration 131 passes the reducibility check. -/
theorem red_cf131 : checkReducible cf131 = true := by decide +kernel

/-- Configuration 132 passes the reducibility check. -/
theorem red_cf132 : checkReducible cf132 = true := by decide +kernel

/-- Configuration 133 passes the reducibility check. -/
theorem red_cf133 : checkReducible cf133 = true := by decide +kernel

/-- Configuration 134 passes the reducibility check. -/
theorem red_cf134 : checkReducible cf134 = true := by decide +kernel

/-- Configuration 135 passes the reducibility check. -/
theorem red_cf135 : checkReducible cf135 = true := by decide +kernel

/-- Configuration 136 passes the reducibility check. -/
theorem red_cf136 : checkReducible cf136 = true := by decide +kernel

/-- Configuration 137 passes the reducibility check. -/
theorem red_cf137 : checkReducible cf137 = true := by decide +kernel

/-- Configuration 138 passes the reducibility check. -/
theorem red_cf138 : checkReducible cf138 = true := by decide +kernel

/-- Configuration 139 passes the reducibility check. -/
theorem red_cf139 : checkReducible cf139 = true := by decide +kernel

/-- Configuration 140 passes the reducibility check. -/
theorem red_cf140 : checkReducible cf140 = true := by decide +kernel

/-- Configuration 141 passes the reducibility check. -/
theorem red_cf141 : checkReducible cf141 = true := by decide +kernel

/-- Configuration 142 passes the reducibility check. -/
theorem red_cf142 : checkReducible cf142 = true := by decide +kernel

/-- Configuration 143 passes the reducibility check. -/
theorem red_cf143 : checkReducible cf143 = true := by decide +kernel

/-- Configuration 144 passes the reducibility check. -/
theorem red_cf144 : checkReducible cf144 = true := by decide +kernel

/-- Configuration 145 passes the reducibility check. -/
theorem red_cf145 : checkReducible cf145 = true := by decide +kernel

/-- Configuration 146 passes the reducibility check. -/
theorem red_cf146 : checkReducible cf146 = true := by decide +kernel

/-- Configuration 147 passes the reducibility check. -/
theorem red_cf147 : checkReducible cf147 = true := by decide +kernel

/-- Configuration 148 passes the reducibility check. -/
theorem red_cf148 : checkReducible cf148 = true := by decide +kernel

/-- Configuration 149 passes the reducibility check. -/
theorem red_cf149 : checkReducible cf149 = true := by decide +kernel

/-- Configuration 150 passes the reducibility check. -/
theorem red_cf150 : checkReducible cf150 = true := by decide +kernel

/-- Configuration 151 passes the reducibility check. -/
theorem red_cf151 : checkReducible cf151 = true := by decide +kernel

/-- Configuration 152 passes the reducibility check. -/
theorem red_cf152 : checkReducible cf152 = true := by decide +kernel

/-- Configuration 153 passes the reducibility check. -/
theorem red_cf153 : checkReducible cf153 = true := by decide +kernel

/-- Configuration 154 passes the reducibility check. -/
theorem red_cf154 : checkReducible cf154 = true := by decide +kernel

/-- Configuration 155 passes the reducibility check. -/
theorem red_cf155 : checkReducible cf155 = true := by decide +kernel

/-- Configuration 156 passes the reducibility check. -/
theorem red_cf156 : checkReducible cf156 = true := by decide +kernel

/-- Configuration 157 passes the reducibility check. -/
theorem red_cf157 : checkReducible cf157 = true := by decide +kernel

/-- Configuration 158 passes the reducibility check. -/
theorem red_cf158 : checkReducible cf158 = true := by decide +kernel

/-- Configuration 159 passes the reducibility check. -/
theorem red_cf159 : checkReducible cf159 = true := by decide +kernel

/-- Configuration 160 passes the reducibility check. -/
theorem red_cf160 : checkReducible cf160 = true := by decide +kernel

/-- Configuration 161 passes the reducibility check. -/
theorem red_cf161 : checkReducible cf161 = true := by decide +kernel

/-- Configuration 162 passes the reducibility check. -/
theorem red_cf162 : checkReducible cf162 = true := by decide +kernel

/-- Configuration 163 passes the reducibility check. -/
theorem red_cf163 : checkReducible cf163 = true := by decide +kernel

/-- Configuration 164 passes the reducibility check. -/
theorem red_cf164 : checkReducible cf164 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 107 to 164 are reducible. -/
theorem red106to164 : ReducibleInRange 106 164 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf107
    | 1 => Or.inr red_cf108
    | 2 => Or.inr red_cf109
    | 3 => Or.inr red_cf110
    | 4 => Or.inr red_cf111
    | 5 => Or.inr red_cf112
    | 6 => Or.inr red_cf113
    | 7 => Or.inr red_cf114
    | 8 => Or.inr red_cf115
    | 9 => Or.inr red_cf116
    | 10 => Or.inr red_cf117
    | 11 => Or.inr red_cf118
    | 12 => Or.inr red_cf119
    | 13 => Or.inr red_cf120
    | 14 => Or.inr red_cf121
    | 15 => Or.inr red_cf122
    | 16 => Or.inr red_cf123
    | 17 => Or.inr red_cf124
    | 18 => Or.inr red_cf125
    | 19 => Or.inr red_cf126
    | 20 => Or.inr red_cf127
    | 21 => Or.inr red_cf128
    | 22 => Or.inr red_cf129
    | 23 => Or.inr red_cf130
    | 24 => Or.inr red_cf131
    | 25 => Or.inr red_cf132
    | 26 => Or.inr red_cf133
    | 27 => Or.inr red_cf134
    | 28 => Or.inr red_cf135
    | 29 => Or.inr red_cf136
    | 30 => Or.inr red_cf137
    | 31 => Or.inr red_cf138
    | 32 => Or.inr red_cf139
    | 33 => Or.inr red_cf140
    | 34 => Or.inr red_cf141
    | 35 => Or.inr red_cf142
    | 36 => Or.inr red_cf143
    | 37 => Or.inr red_cf144
    | 38 => Or.inr red_cf145
    | 39 => Or.inr red_cf146
    | 40 => Or.inr red_cf147
    | 41 => Or.inr red_cf148
    | 42 => Or.inr red_cf149
    | 43 => Or.inr red_cf150
    | 44 => Or.inr red_cf151
    | 45 => Or.inr red_cf152
    | 46 => Or.inr red_cf153
    | 47 => Or.inr red_cf154
    | 48 => Or.inr red_cf155
    | 49 => Or.inr red_cf156
    | 50 => Or.inr red_cf157
    | 51 => Or.inr red_cf158
    | 52 => Or.inr red_cf159
    | 53 => Or.inr red_cf160
    | 54 => Or.inr red_cf161
    | 55 => Or.inr red_cf162
    | 56 => Or.inr red_cf163
    | 57 => Or.inr red_cf164
    | n + 58 => Or.inl (Nat.le_add_left 58 n)

end FourColor
