import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 165 to 189, whose indices in `theConfigs` range over
the segment `[164, 189)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job165to189.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 165 passes the reducibility check. -/
theorem red_cf165 : checkReducible cf165 = true := by decide +kernel

/-- Configuration 166 passes the reducibility check. -/
theorem red_cf166 : checkReducible cf166 = true := by decide +kernel

/-- Configuration 167 passes the reducibility check. -/
theorem red_cf167 : checkReducible cf167 = true := by decide +kernel

/-- Configuration 168 passes the reducibility check. -/
theorem red_cf168 : checkReducible cf168 = true := by decide +kernel

/-- Configuration 169 passes the reducibility check. -/
theorem red_cf169 : checkReducible cf169 = true := by decide +kernel

/-- Configuration 170 passes the reducibility check. -/
theorem red_cf170 : checkReducible cf170 = true := by decide +kernel

/-- Configuration 171 passes the reducibility check. -/
theorem red_cf171 : checkReducible cf171 = true := by decide +kernel

/-- Configuration 172 passes the reducibility check. -/
theorem red_cf172 : checkReducible cf172 = true := by decide +kernel

/-- Configuration 173 passes the reducibility check. -/
theorem red_cf173 : checkReducible cf173 = true := by decide +kernel

/-- Configuration 174 passes the reducibility check. -/
theorem red_cf174 : checkReducible cf174 = true := by decide +kernel

/-- Configuration 175 passes the reducibility check. -/
theorem red_cf175 : checkReducible cf175 = true := by decide +kernel

/-- Configuration 176 passes the reducibility check. -/
theorem red_cf176 : checkReducible cf176 = true := by decide +kernel

/-- Configuration 177 passes the reducibility check. -/
theorem red_cf177 : checkReducible cf177 = true := by decide +kernel

/-- Configuration 178 passes the reducibility check. -/
theorem red_cf178 : checkReducible cf178 = true := by decide +kernel

/-- Configuration 179 passes the reducibility check. -/
theorem red_cf179 : checkReducible cf179 = true := by decide +kernel

/-- Configuration 180 passes the reducibility check. -/
theorem red_cf180 : checkReducible cf180 = true := by decide +kernel

/-- Configuration 181 passes the reducibility check. -/
theorem red_cf181 : checkReducible cf181 = true := by decide +kernel

/-- Configuration 182 passes the reducibility check. -/
theorem red_cf182 : checkReducible cf182 = true := by decide +kernel

/-- Configuration 183 passes the reducibility check. -/
theorem red_cf183 : checkReducible cf183 = true := by decide +kernel

/-- Configuration 184 passes the reducibility check. -/
theorem red_cf184 : checkReducible cf184 = true := by decide +kernel

/-- Configuration 185 passes the reducibility check. -/
theorem red_cf185 : checkReducible cf185 = true := by decide +kernel

/-- Configuration 186 passes the reducibility check. -/
theorem red_cf186 : checkReducible cf186 = true := by decide +kernel

/-- Configuration 187 passes the reducibility check. -/
theorem red_cf187 : checkReducible cf187 = true := by decide +kernel

/-- Configuration 188 passes the reducibility check. -/
theorem red_cf188 : checkReducible cf188 = true := by decide +kernel

/-- Configuration 189 passes the reducibility check. -/
theorem red_cf189 : checkReducible cf189 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 165 to 189 are reducible. -/
theorem red164to189 : ReducibleInRange 164 189 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf165
    | 1 => Or.inr red_cf166
    | 2 => Or.inr red_cf167
    | 3 => Or.inr red_cf168
    | 4 => Or.inr red_cf169
    | 5 => Or.inr red_cf170
    | 6 => Or.inr red_cf171
    | 7 => Or.inr red_cf172
    | 8 => Or.inr red_cf173
    | 9 => Or.inr red_cf174
    | 10 => Or.inr red_cf175
    | 11 => Or.inr red_cf176
    | 12 => Or.inr red_cf177
    | 13 => Or.inr red_cf178
    | 14 => Or.inr red_cf179
    | 15 => Or.inr red_cf180
    | 16 => Or.inr red_cf181
    | 17 => Or.inr red_cf182
    | 18 => Or.inr red_cf183
    | 19 => Or.inr red_cf184
    | 20 => Or.inr red_cf185
    | 21 => Or.inr red_cf186
    | 22 => Or.inr red_cf187
    | 23 => Or.inr red_cf188
    | 24 => Or.inr red_cf189
    | n + 25 => Or.inl (Nat.le_add_left 25 n)

end FourColor
