import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 283 to 286, whose indices in `theConfigs` range over
the segment `[282, 286)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job283to286.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 283 passes the reducibility check. -/
theorem red_cf283 : checkReducible cf283 = true := by decide +kernel

/-- Configuration 284 passes the reducibility check. -/
theorem red_cf284 : checkReducible cf284 = true := by decide +kernel

/-- Configuration 285 passes the reducibility check. -/
theorem red_cf285 : checkReducible cf285 = true := by decide +kernel

/-- Configuration 286 passes the reducibility check. -/
theorem red_cf286 : checkReducible cf286 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 283 to 286 are reducible. -/
theorem red282to286 : ReducibleInRange 282 286 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf283
    | 1 => Or.inr red_cf284
    | 2 => Or.inr red_cf285
    | 3 => Or.inr red_cf286
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
