import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 239 to 253, whose indices in `theConfigs` range over
the segment `[238, 253)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job239to253.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 239 passes the reducibility check. -/
theorem red_cf239 : checkReducible cf239 = true := by decide +kernel

/-- Configuration 240 passes the reducibility check. -/
theorem red_cf240 : checkReducible cf240 = true := by decide +kernel

/-- Configuration 241 passes the reducibility check. -/
theorem red_cf241 : checkReducible cf241 = true := by decide +kernel

/-- Configuration 242 passes the reducibility check. -/
theorem red_cf242 : checkReducible cf242 = true := by decide +kernel

/-- Configuration 243 passes the reducibility check. -/
theorem red_cf243 : checkReducible cf243 = true := by decide +kernel

/-- Configuration 244 passes the reducibility check. -/
theorem red_cf244 : checkReducible cf244 = true := by decide +kernel

/-- Configuration 245 passes the reducibility check. -/
theorem red_cf245 : checkReducible cf245 = true := by decide +kernel

/-- Configuration 246 passes the reducibility check. -/
theorem red_cf246 : checkReducible cf246 = true := by decide +kernel

/-- Configuration 247 passes the reducibility check. -/
theorem red_cf247 : checkReducible cf247 = true := by decide +kernel

/-- Configuration 248 passes the reducibility check. -/
theorem red_cf248 : checkReducible cf248 = true := by decide +kernel

/-- Configuration 249 passes the reducibility check. -/
theorem red_cf249 : checkReducible cf249 = true := by decide +kernel

/-- Configuration 250 passes the reducibility check. -/
theorem red_cf250 : checkReducible cf250 = true := by decide +kernel

/-- Configuration 251 passes the reducibility check. -/
theorem red_cf251 : checkReducible cf251 = true := by decide +kernel

/-- Configuration 252 passes the reducibility check. -/
theorem red_cf252 : checkReducible cf252 = true := by decide +kernel

/-- Configuration 253 passes the reducibility check. -/
theorem red_cf253 : checkReducible cf253 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 239 to 253 are reducible. -/
theorem red238to253 : ReducibleInRange 238 253 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf239
    | 1 => Or.inr red_cf240
    | 2 => Or.inr red_cf241
    | 3 => Or.inr red_cf242
    | 4 => Or.inr red_cf243
    | 5 => Or.inr red_cf244
    | 6 => Or.inr red_cf245
    | 7 => Or.inr red_cf246
    | 8 => Or.inr red_cf247
    | 9 => Or.inr red_cf248
    | 10 => Or.inr red_cf249
    | 11 => Or.inr red_cf250
    | 12 => Or.inr red_cf251
    | 13 => Or.inr red_cf252
    | 14 => Or.inr red_cf253
    | n + 15 => Or.inl (Nat.le_add_left 15 n)

end FourColor
