import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 223 to 226, whose indices in `theConfigs` range over
the segment `[222, 226)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job223to226.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 223 passes the reducibility check. -/
theorem red_cf223 : checkReducible cf223 = true := by decide +kernel

/-- Configuration 224 passes the reducibility check. -/
theorem red_cf224 : checkReducible cf224 = true := by decide +kernel

/-- Configuration 225 passes the reducibility check. -/
theorem red_cf225 : checkReducible cf225 = true := by decide +kernel

/-- Configuration 226 passes the reducibility check. -/
theorem red_cf226 : checkReducible cf226 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 223 to 226 are reducible. -/
theorem red222to226 : ReducibleInRange 222 226 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf223
    | 1 => Or.inr red_cf224
    | 2 => Or.inr red_cf225
    | 3 => Or.inr red_cf226
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
