import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 227 to 230, whose indices in `theConfigs` range over
the segment `[226, 230)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job227to230.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 227 passes the reducibility check. -/
theorem red_cf227 : checkReducible cf227 = true := by decide +kernel

/-- Configuration 228 passes the reducibility check. -/
theorem red_cf228 : checkReducible cf228 = true := by decide +kernel

/-- Configuration 229 passes the reducibility check. -/
theorem red_cf229 : checkReducible cf229 = true := by decide +kernel

/-- Configuration 230 passes the reducibility check. -/
theorem red_cf230 : checkReducible cf230 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 227 to 230 are reducible. -/
theorem red226to230 : ReducibleInRange 226 230 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf227
    | 1 => Or.inr red_cf228
    | 2 => Or.inr red_cf229
    | 3 => Or.inr red_cf230
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
