import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 299 to 302, whose indices in `theConfigs` range over
the segment `[298, 302)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job299to302.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 299 passes the reducibility check. -/
theorem red_cf299 : checkReducible cf299 = true := by decide +kernel

/-- Configuration 300 passes the reducibility check. -/
theorem red_cf300 : checkReducible cf300 = true := by decide +kernel

/-- Configuration 301 passes the reducibility check. -/
theorem red_cf301 : checkReducible cf301 = true := by decide +kernel

/-- Configuration 302 passes the reducibility check. -/
theorem red_cf302 : checkReducible cf302 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 299 to 302 are reducible. -/
theorem red298to302 : ReducibleInRange 298 302 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf299
    | 1 => Or.inr red_cf300
    | 2 => Or.inr red_cf301
    | 3 => Or.inr red_cf302
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
