import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 215 to 218, whose indices in `theConfigs` range over
the segment `[214, 218)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job215to218.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 215 passes the reducibility check. -/
theorem red_cf215 : checkReducible cf215 = true := by decide +kernel

/-- Configuration 216 passes the reducibility check. -/
theorem red_cf216 : checkReducible cf216 = true := by decide +kernel

/-- Configuration 217 passes the reducibility check. -/
theorem red_cf217 : checkReducible cf217 = true := by decide +kernel

/-- Configuration 218 passes the reducibility check. -/
theorem red_cf218 : checkReducible cf218 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 215 to 218 are reducible. -/
theorem red214to218 : ReducibleInRange 214 218 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf215
    | 1 => Or.inr red_cf216
    | 2 => Or.inr red_cf217
    | 3 => Or.inr red_cf218
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
