import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 291 to 294, whose indices in `theConfigs` range over
the segment `[290, 294)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job291to294.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 291 passes the reducibility check. -/
theorem red_cf291 : checkReducible cf291 = true := by decide +kernel

/-- Configuration 292 passes the reducibility check. -/
theorem red_cf292 : checkReducible cf292 = true := by decide +kernel

/-- Configuration 293 passes the reducibility check. -/
theorem red_cf293 : checkReducible cf293 = true := by decide +kernel

/-- Configuration 294 passes the reducibility check. -/
theorem red_cf294 : checkReducible cf294 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 291 to 294 are reducible. -/
theorem red290to294 : ReducibleInRange 290 294 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf291
    | 1 => Or.inr red_cf292
    | 2 => Or.inr red_cf293
    | 3 => Or.inr red_cf294
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
