import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 287 to 290, whose indices in `theConfigs` range over
the segment `[286, 290)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job287to290.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 287 passes the reducibility check. -/
theorem red_cf287 : checkReducible cf287 = true := by decide +kernel

/-- Configuration 288 passes the reducibility check. -/
theorem red_cf288 : checkReducible cf288 = true := by decide +kernel

/-- Configuration 289 passes the reducibility check. -/
theorem red_cf289 : checkReducible cf289 = true := by decide +kernel

/-- Configuration 290 passes the reducibility check. -/
theorem red_cf290 : checkReducible cf290 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 287 to 290 are reducible. -/
theorem red286to290 : ReducibleInRange 286 290 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf287
    | 1 => Or.inr red_cf288
    | 2 => Or.inr red_cf289
    | 3 => Or.inr red_cf290
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
