import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 235 to 238, whose indices in `theConfigs` range over
the segment `[234, 238)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job235to238.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 235 passes the reducibility check. -/
theorem red_cf235 : checkReducible cf235 = true := by decide +kernel

/-- Configuration 236 passes the reducibility check. -/
theorem red_cf236 : checkReducible cf236 = true := by decide +kernel

/-- Configuration 237 passes the reducibility check. -/
theorem red_cf237 : checkReducible cf237 = true := by decide +kernel

/-- Configuration 238 passes the reducibility check. -/
theorem red_cf238 : checkReducible cf238 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 235 to 238 are reducible. -/
theorem red234to238 : ReducibleInRange 234 238 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf235
    | 1 => Or.inr red_cf236
    | 2 => Or.inr red_cf237
    | 3 => Or.inr red_cf238
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
