import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 231 to 234, whose indices in `theConfigs` range over
the segment `[230, 234)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job231to234.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 231 passes the reducibility check. -/
theorem red_cf231 : checkReducible cf231 = true := by decide +kernel

/-- Configuration 232 passes the reducibility check. -/
theorem red_cf232 : checkReducible cf232 = true := by decide +kernel

/-- Configuration 233 passes the reducibility check. -/
theorem red_cf233 : checkReducible cf233 = true := by decide +kernel

/-- Configuration 234 passes the reducibility check. -/
theorem red_cf234 : checkReducible cf234 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 231 to 234 are reducible. -/
theorem red230to234 : ReducibleInRange 230 234 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf231
    | 1 => Or.inr red_cf232
    | 2 => Or.inr red_cf233
    | 3 => Or.inr red_cf234
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
