import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 219 to 222, whose indices in `theConfigs` range over
the segment `[218, 222)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job219to222.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 219 passes the reducibility check. -/
theorem red_cf219 : checkReducible cf219 = true := by decide +kernel

/-- Configuration 220 passes the reducibility check. -/
theorem red_cf220 : checkReducible cf220 = true := by decide +kernel

/-- Configuration 221 passes the reducibility check. -/
theorem red_cf221 : checkReducible cf221 = true := by decide +kernel

/-- Configuration 222 passes the reducibility check. -/
theorem red_cf222 : checkReducible cf222 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 219 to 222 are reducible. -/
theorem red218to222 : ReducibleInRange 218 222 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf219
    | 1 => Or.inr red_cf220
    | 2 => Or.inr red_cf221
    | 3 => Or.inr red_cf222
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
