import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 254 to 270, whose indices in `theConfigs` range over
the segment `[253, 270)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job254to270.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 254 passes the reducibility check. -/
theorem red_cf254 : checkReducible cf254 = true := by decide +kernel

/-- Configuration 255 passes the reducibility check. -/
theorem red_cf255 : checkReducible cf255 = true := by decide +kernel

/-- Configuration 256 passes the reducibility check. -/
theorem red_cf256 : checkReducible cf256 = true := by decide +kernel

/-- Configuration 257 passes the reducibility check. -/
theorem red_cf257 : checkReducible cf257 = true := by decide +kernel

/-- Configuration 258 passes the reducibility check. -/
theorem red_cf258 : checkReducible cf258 = true := by decide +kernel

/-- Configuration 259 passes the reducibility check. -/
theorem red_cf259 : checkReducible cf259 = true := by decide +kernel

/-- Configuration 260 passes the reducibility check. -/
theorem red_cf260 : checkReducible cf260 = true := by decide +kernel

/-- Configuration 261 passes the reducibility check. -/
theorem red_cf261 : checkReducible cf261 = true := by decide +kernel

/-- Configuration 262 passes the reducibility check. -/
theorem red_cf262 : checkReducible cf262 = true := by decide +kernel

/-- Configuration 263 passes the reducibility check. -/
theorem red_cf263 : checkReducible cf263 = true := by decide +kernel

/-- Configuration 264 passes the reducibility check. -/
theorem red_cf264 : checkReducible cf264 = true := by decide +kernel

/-- Configuration 265 passes the reducibility check. -/
theorem red_cf265 : checkReducible cf265 = true := by decide +kernel

/-- Configuration 266 passes the reducibility check. -/
theorem red_cf266 : checkReducible cf266 = true := by decide +kernel

/-- Configuration 267 passes the reducibility check. -/
theorem red_cf267 : checkReducible cf267 = true := by decide +kernel

/-- Configuration 268 passes the reducibility check. -/
theorem red_cf268 : checkReducible cf268 = true := by decide +kernel

/-- Configuration 269 passes the reducibility check. -/
theorem red_cf269 : checkReducible cf269 = true := by decide +kernel

/-- Configuration 270 passes the reducibility check. -/
theorem red_cf270 : checkReducible cf270 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 254 to 270 are reducible. -/
theorem red253to270 : ReducibleInRange 253 270 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf254
    | 1 => Or.inr red_cf255
    | 2 => Or.inr red_cf256
    | 3 => Or.inr red_cf257
    | 4 => Or.inr red_cf258
    | 5 => Or.inr red_cf259
    | 6 => Or.inr red_cf260
    | 7 => Or.inr red_cf261
    | 8 => Or.inr red_cf262
    | 9 => Or.inr red_cf263
    | 10 => Or.inr red_cf264
    | 11 => Or.inr red_cf265
    | 12 => Or.inr red_cf266
    | 13 => Or.inr red_cf267
    | 14 => Or.inr red_cf268
    | 15 => Or.inr red_cf269
    | 16 => Or.inr red_cf270
    | n + 17 => Or.inl (Nat.le_add_left 17 n)

end FourColor
