import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 271 to 278, whose indices in `theConfigs` range over
the segment `[270, 278)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job271to278.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 271 passes the reducibility check. -/
theorem red_cf271 : checkReducible cf271 = true := by decide +kernel

/-- Configuration 272 passes the reducibility check. -/
theorem red_cf272 : checkReducible cf272 = true := by decide +kernel

/-- Configuration 273 passes the reducibility check. -/
theorem red_cf273 : checkReducible cf273 = true := by decide +kernel

/-- Configuration 274 passes the reducibility check. -/
theorem red_cf274 : checkReducible cf274 = true := by decide +kernel

/-- Configuration 275 passes the reducibility check. -/
theorem red_cf275 : checkReducible cf275 = true := by decide +kernel

/-- Configuration 276 passes the reducibility check. -/
theorem red_cf276 : checkReducible cf276 = true := by decide +kernel

/-- Configuration 277 passes the reducibility check. -/
theorem red_cf277 : checkReducible cf277 = true := by decide +kernel

/-- Configuration 278 passes the reducibility check. -/
theorem red_cf278 : checkReducible cf278 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 271 to 278 are reducible. -/
theorem red270to278 : ReducibleInRange 270 278 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf271
    | 1 => Or.inr red_cf272
    | 2 => Or.inr red_cf273
    | 3 => Or.inr red_cf274
    | 4 => Or.inr red_cf275
    | 5 => Or.inr red_cf276
    | 6 => Or.inr red_cf277
    | 7 => Or.inr red_cf278
    | n + 8 => Or.inl (Nat.le_add_left 8 n)

end FourColor
