import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 295 to 298, whose indices in `theConfigs` range over
the segment `[294, 298)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job295to298.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 295 passes the reducibility check. -/
theorem red_cf295 : checkReducible cf295 = true := by decide +kernel

/-- Configuration 296 passes the reducibility check. -/
theorem red_cf296 : checkReducible cf296 = true := by decide +kernel

/-- Configuration 297 passes the reducibility check. -/
theorem red_cf297 : checkReducible cf297 = true := by decide +kernel

/-- Configuration 298 passes the reducibility check. -/
theorem red_cf298 : checkReducible cf298 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 295 to 298 are reducible. -/
theorem red294to298 : ReducibleInRange 294 298 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf295
    | 1 => Or.inr red_cf296
    | 2 => Or.inr red_cf297
    | 3 => Or.inr red_cf298
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
