import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 207 to 214, whose indices in `theConfigs` range over
the segment `[206, 214)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job207to214.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 207 passes the reducibility check. -/
theorem red_cf207 : checkReducible cf207 = true := by decide +kernel

/-- Configuration 208 passes the reducibility check. -/
theorem red_cf208 : checkReducible cf208 = true := by decide +kernel

/-- Configuration 209 passes the reducibility check. -/
theorem red_cf209 : checkReducible cf209 = true := by decide +kernel

/-- Configuration 210 passes the reducibility check. -/
theorem red_cf210 : checkReducible cf210 = true := by decide +kernel

/-- Configuration 211 passes the reducibility check. -/
theorem red_cf211 : checkReducible cf211 = true := by decide +kernel

/-- Configuration 212 passes the reducibility check. -/
theorem red_cf212 : checkReducible cf212 = true := by decide +kernel

/-- Configuration 213 passes the reducibility check. -/
theorem red_cf213 : checkReducible cf213 = true := by decide +kernel

/-- Configuration 214 passes the reducibility check. -/
theorem red_cf214 : checkReducible cf214 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 207 to 214 are reducible. -/
theorem red206to214 : ReducibleInRange 206 214 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf207
    | 1 => Or.inr red_cf208
    | 2 => Or.inr red_cf209
    | 3 => Or.inr red_cf210
    | 4 => Or.inr red_cf211
    | 5 => Or.inr red_cf212
    | 6 => Or.inr red_cf213
    | 7 => Or.inr red_cf214
    | n + 8 => Or.inl (Nat.le_add_left 8 n)

end FourColor
