import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 279 to 282, whose indices in `theConfigs` range over
the segment `[278, 282)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job279to282.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 279 passes the reducibility check. -/
theorem red_cf279 : checkReducible cf279 = true := by decide +kernel

/-- Configuration 280 passes the reducibility check. -/
theorem red_cf280 : checkReducible cf280 = true := by decide +kernel

/-- Configuration 281 passes the reducibility check. -/
theorem red_cf281 : checkReducible cf281 = true := by decide +kernel

/-- Configuration 282 passes the reducibility check. -/
theorem red_cf282 : checkReducible cf282 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 279 to 282 are reducible. -/
theorem red278to282 : ReducibleInRange 278 282 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf279
    | 1 => Or.inr red_cf280
    | 2 => Or.inr red_cf281
    | 3 => Or.inr red_cf282
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
