import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 323 to 383, whose indices in `theConfigs` range over
the segment `[322, 383)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job323to383.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 323 passes the reducibility check. -/
theorem red_cf323 : checkReducible cf323 = true := by decide +kernel

/-- Configuration 324 passes the reducibility check. -/
theorem red_cf324 : checkReducible cf324 = true := by decide +kernel

/-- Configuration 325 passes the reducibility check. -/
theorem red_cf325 : checkReducible cf325 = true := by decide +kernel

/-- Configuration 326 passes the reducibility check. -/
theorem red_cf326 : checkReducible cf326 = true := by decide +kernel

/-- Configuration 327 passes the reducibility check. -/
theorem red_cf327 : checkReducible cf327 = true := by decide +kernel

/-- Configuration 328 passes the reducibility check. -/
theorem red_cf328 : checkReducible cf328 = true := by decide +kernel

/-- Configuration 329 passes the reducibility check. -/
theorem red_cf329 : checkReducible cf329 = true := by decide +kernel

/-- Configuration 330 passes the reducibility check. -/
theorem red_cf330 : checkReducible cf330 = true := by decide +kernel

/-- Configuration 331 passes the reducibility check. -/
theorem red_cf331 : checkReducible cf331 = true := by decide +kernel

/-- Configuration 332 passes the reducibility check. -/
theorem red_cf332 : checkReducible cf332 = true := by decide +kernel

/-- Configuration 333 passes the reducibility check. -/
theorem red_cf333 : checkReducible cf333 = true := by decide +kernel

/-- Configuration 334 passes the reducibility check. -/
theorem red_cf334 : checkReducible cf334 = true := by decide +kernel

/-- Configuration 335 passes the reducibility check. -/
theorem red_cf335 : checkReducible cf335 = true := by decide +kernel

/-- Configuration 336 passes the reducibility check. -/
theorem red_cf336 : checkReducible cf336 = true := by decide +kernel

/-- Configuration 337 passes the reducibility check. -/
theorem red_cf337 : checkReducible cf337 = true := by decide +kernel

/-- Configuration 338 passes the reducibility check. -/
theorem red_cf338 : checkReducible cf338 = true := by decide +kernel

/-- Configuration 339 passes the reducibility check. -/
theorem red_cf339 : checkReducible cf339 = true := by decide +kernel

/-- Configuration 340 passes the reducibility check. -/
theorem red_cf340 : checkReducible cf340 = true := by decide +kernel

/-- Configuration 341 passes the reducibility check. -/
theorem red_cf341 : checkReducible cf341 = true := by decide +kernel

/-- Configuration 342 passes the reducibility check. -/
theorem red_cf342 : checkReducible cf342 = true := by decide +kernel

/-- Configuration 343 passes the reducibility check. -/
theorem red_cf343 : checkReducible cf343 = true := by decide +kernel

/-- Configuration 344 passes the reducibility check. -/
theorem red_cf344 : checkReducible cf344 = true := by decide +kernel

/-- Configuration 345 passes the reducibility check. -/
theorem red_cf345 : checkReducible cf345 = true := by decide +kernel

/-- Configuration 346 passes the reducibility check. -/
theorem red_cf346 : checkReducible cf346 = true := by decide +kernel

/-- Configuration 347 passes the reducibility check. -/
theorem red_cf347 : checkReducible cf347 = true := by decide +kernel

/-- Configuration 348 passes the reducibility check. -/
theorem red_cf348 : checkReducible cf348 = true := by decide +kernel

/-- Configuration 349 passes the reducibility check. -/
theorem red_cf349 : checkReducible cf349 = true := by decide +kernel

/-- Configuration 350 passes the reducibility check. -/
theorem red_cf350 : checkReducible cf350 = true := by decide +kernel

/-- Configuration 351 passes the reducibility check. -/
theorem red_cf351 : checkReducible cf351 = true := by decide +kernel

/-- Configuration 352 passes the reducibility check. -/
theorem red_cf352 : checkReducible cf352 = true := by decide +kernel

/-- Configuration 353 passes the reducibility check. -/
theorem red_cf353 : checkReducible cf353 = true := by decide +kernel

/-- Configuration 354 passes the reducibility check. -/
theorem red_cf354 : checkReducible cf354 = true := by decide +kernel

/-- Configuration 355 passes the reducibility check. -/
theorem red_cf355 : checkReducible cf355 = true := by decide +kernel

/-- Configuration 356 passes the reducibility check. -/
theorem red_cf356 : checkReducible cf356 = true := by decide +kernel

/-- Configuration 357 passes the reducibility check. -/
theorem red_cf357 : checkReducible cf357 = true := by decide +kernel

/-- Configuration 358 passes the reducibility check. -/
theorem red_cf358 : checkReducible cf358 = true := by decide +kernel

/-- Configuration 359 passes the reducibility check. -/
theorem red_cf359 : checkReducible cf359 = true := by decide +kernel

/-- Configuration 360 passes the reducibility check. -/
theorem red_cf360 : checkReducible cf360 = true := by decide +kernel

/-- Configuration 361 passes the reducibility check. -/
theorem red_cf361 : checkReducible cf361 = true := by decide +kernel

/-- Configuration 362 passes the reducibility check. -/
theorem red_cf362 : checkReducible cf362 = true := by decide +kernel

/-- Configuration 363 passes the reducibility check. -/
theorem red_cf363 : checkReducible cf363 = true := by decide +kernel

/-- Configuration 364 passes the reducibility check. -/
theorem red_cf364 : checkReducible cf364 = true := by decide +kernel

/-- Configuration 365 passes the reducibility check. -/
theorem red_cf365 : checkReducible cf365 = true := by decide +kernel

/-- Configuration 366 passes the reducibility check. -/
theorem red_cf366 : checkReducible cf366 = true := by decide +kernel

/-- Configuration 367 passes the reducibility check. -/
theorem red_cf367 : checkReducible cf367 = true := by decide +kernel

/-- Configuration 368 passes the reducibility check. -/
theorem red_cf368 : checkReducible cf368 = true := by decide +kernel

/-- Configuration 369 passes the reducibility check. -/
theorem red_cf369 : checkReducible cf369 = true := by decide +kernel

/-- Configuration 370 passes the reducibility check. -/
theorem red_cf370 : checkReducible cf370 = true := by decide +kernel

/-- Configuration 371 passes the reducibility check. -/
theorem red_cf371 : checkReducible cf371 = true := by decide +kernel

/-- Configuration 372 passes the reducibility check. -/
theorem red_cf372 : checkReducible cf372 = true := by decide +kernel

/-- Configuration 373 passes the reducibility check. -/
theorem red_cf373 : checkReducible cf373 = true := by decide +kernel

/-- Configuration 374 passes the reducibility check. -/
theorem red_cf374 : checkReducible cf374 = true := by decide +kernel

/-- Configuration 375 passes the reducibility check. -/
theorem red_cf375 : checkReducible cf375 = true := by decide +kernel

/-- Configuration 376 passes the reducibility check. -/
theorem red_cf376 : checkReducible cf376 = true := by decide +kernel

/-- Configuration 377 passes the reducibility check. -/
theorem red_cf377 : checkReducible cf377 = true := by decide +kernel

/-- Configuration 378 passes the reducibility check. -/
theorem red_cf378 : checkReducible cf378 = true := by decide +kernel

/-- Configuration 379 passes the reducibility check. -/
theorem red_cf379 : checkReducible cf379 = true := by decide +kernel

/-- Configuration 380 passes the reducibility check. -/
theorem red_cf380 : checkReducible cf380 = true := by decide +kernel

/-- Configuration 381 passes the reducibility check. -/
theorem red_cf381 : checkReducible cf381 = true := by decide +kernel

/-- Configuration 382 passes the reducibility check. -/
theorem red_cf382 : checkReducible cf382 = true := by decide +kernel

/-- Configuration 383 passes the reducibility check. -/
theorem red_cf383 : checkReducible cf383 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 323 to 383 are reducible. -/
theorem red322to383 : ReducibleInRange 322 383 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf323
    | 1 => Or.inr red_cf324
    | 2 => Or.inr red_cf325
    | 3 => Or.inr red_cf326
    | 4 => Or.inr red_cf327
    | 5 => Or.inr red_cf328
    | 6 => Or.inr red_cf329
    | 7 => Or.inr red_cf330
    | 8 => Or.inr red_cf331
    | 9 => Or.inr red_cf332
    | 10 => Or.inr red_cf333
    | 11 => Or.inr red_cf334
    | 12 => Or.inr red_cf335
    | 13 => Or.inr red_cf336
    | 14 => Or.inr red_cf337
    | 15 => Or.inr red_cf338
    | 16 => Or.inr red_cf339
    | 17 => Or.inr red_cf340
    | 18 => Or.inr red_cf341
    | 19 => Or.inr red_cf342
    | 20 => Or.inr red_cf343
    | 21 => Or.inr red_cf344
    | 22 => Or.inr red_cf345
    | 23 => Or.inr red_cf346
    | 24 => Or.inr red_cf347
    | 25 => Or.inr red_cf348
    | 26 => Or.inr red_cf349
    | 27 => Or.inr red_cf350
    | 28 => Or.inr red_cf351
    | 29 => Or.inr red_cf352
    | 30 => Or.inr red_cf353
    | 31 => Or.inr red_cf354
    | 32 => Or.inr red_cf355
    | 33 => Or.inr red_cf356
    | 34 => Or.inr red_cf357
    | 35 => Or.inr red_cf358
    | 36 => Or.inr red_cf359
    | 37 => Or.inr red_cf360
    | 38 => Or.inr red_cf361
    | 39 => Or.inr red_cf362
    | 40 => Or.inr red_cf363
    | 41 => Or.inr red_cf364
    | 42 => Or.inr red_cf365
    | 43 => Or.inr red_cf366
    | 44 => Or.inr red_cf367
    | 45 => Or.inr red_cf368
    | 46 => Or.inr red_cf369
    | 47 => Or.inr red_cf370
    | 48 => Or.inr red_cf371
    | 49 => Or.inr red_cf372
    | 50 => Or.inr red_cf373
    | 51 => Or.inr red_cf374
    | 52 => Or.inr red_cf375
    | 53 => Or.inr red_cf376
    | 54 => Or.inr red_cf377
    | 55 => Or.inr red_cf378
    | 56 => Or.inr red_cf379
    | 57 => Or.inr red_cf380
    | 58 => Or.inr red_cf381
    | 59 => Or.inr red_cf382
    | 60 => Or.inr red_cf383
    | n + 61 => Or.inl (Nat.le_add_left 61 n)

end FourColor
