import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 384 to 398, whose indices in `theConfigs` range over
the segment `[383, 398)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job384to398.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 384 passes the reducibility check. -/
theorem red_cf384 : checkReducible cf384 = true := by decide +kernel

/-- Configuration 385 passes the reducibility check. -/
theorem red_cf385 : checkReducible cf385 = true := by decide +kernel

/-- Configuration 386 passes the reducibility check. -/
theorem red_cf386 : checkReducible cf386 = true := by decide +kernel

/-- Configuration 387 passes the reducibility check. -/
theorem red_cf387 : checkReducible cf387 = true := by decide +kernel

/-- Configuration 388 passes the reducibility check. -/
theorem red_cf388 : checkReducible cf388 = true := by decide +kernel

/-- Configuration 389 passes the reducibility check. -/
theorem red_cf389 : checkReducible cf389 = true := by decide +kernel

/-- Configuration 390 passes the reducibility check. -/
theorem red_cf390 : checkReducible cf390 = true := by decide +kernel

/-- Configuration 391 passes the reducibility check. -/
theorem red_cf391 : checkReducible cf391 = true := by decide +kernel

/-- Configuration 392 passes the reducibility check. -/
theorem red_cf392 : checkReducible cf392 = true := by decide +kernel

/-- Configuration 393 passes the reducibility check. -/
theorem red_cf393 : checkReducible cf393 = true := by decide +kernel

/-- Configuration 394 passes the reducibility check. -/
theorem red_cf394 : checkReducible cf394 = true := by decide +kernel

/-- Configuration 395 passes the reducibility check. -/
theorem red_cf395 : checkReducible cf395 = true := by decide +kernel

/-- Configuration 396 passes the reducibility check. -/
theorem red_cf396 : checkReducible cf396 = true := by decide +kernel

/-- Configuration 397 passes the reducibility check. -/
theorem red_cf397 : checkReducible cf397 = true := by decide +kernel

/-- Configuration 398 passes the reducibility check. -/
theorem red_cf398 : checkReducible cf398 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 384 to 398 are reducible. -/
theorem red383to398 : ReducibleInRange 383 398 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf384
    | 1 => Or.inr red_cf385
    | 2 => Or.inr red_cf386
    | 3 => Or.inr red_cf387
    | 4 => Or.inr red_cf388
    | 5 => Or.inr red_cf389
    | 6 => Or.inr red_cf390
    | 7 => Or.inr red_cf391
    | 8 => Or.inr red_cf392
    | 9 => Or.inr red_cf393
    | 10 => Or.inr red_cf394
    | 11 => Or.inr red_cf395
    | 12 => Or.inr red_cf396
    | 13 => Or.inr red_cf397
    | 14 => Or.inr red_cf398
    | n + 15 => Or.inl (Nat.le_add_left 15 n)

end FourColor
