import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 399 to 438, whose indices in `theConfigs` range over
the segment `[398, 438)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job399to438.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 399 passes the reducibility check. -/
theorem red_cf399 : checkReducible cf399 = true := by decide +kernel

/-- Configuration 400 passes the reducibility check. -/
theorem red_cf400 : checkReducible cf400 = true := by decide +kernel

/-- Configuration 401 passes the reducibility check. -/
theorem red_cf401 : checkReducible cf401 = true := by decide +kernel

/-- Configuration 402 passes the reducibility check. -/
theorem red_cf402 : checkReducible cf402 = true := by decide +kernel

/-- Configuration 403 passes the reducibility check. -/
theorem red_cf403 : checkReducible cf403 = true := by decide +kernel

/-- Configuration 404 passes the reducibility check. -/
theorem red_cf404 : checkReducible cf404 = true := by decide +kernel

/-- Configuration 405 passes the reducibility check. -/
theorem red_cf405 : checkReducible cf405 = true := by decide +kernel

/-- Configuration 406 passes the reducibility check. -/
theorem red_cf406 : checkReducible cf406 = true := by decide +kernel

/-- Configuration 407 passes the reducibility check. -/
theorem red_cf407 : checkReducible cf407 = true := by decide +kernel

/-- Configuration 408 passes the reducibility check. -/
theorem red_cf408 : checkReducible cf408 = true := by decide +kernel

/-- Configuration 409 passes the reducibility check. -/
theorem red_cf409 : checkReducible cf409 = true := by decide +kernel

/-- Configuration 410 passes the reducibility check. -/
theorem red_cf410 : checkReducible cf410 = true := by decide +kernel

/-- Configuration 411 passes the reducibility check. -/
theorem red_cf411 : checkReducible cf411 = true := by decide +kernel

/-- Configuration 412 passes the reducibility check. -/
theorem red_cf412 : checkReducible cf412 = true := by decide +kernel

/-- Configuration 413 passes the reducibility check. -/
theorem red_cf413 : checkReducible cf413 = true := by decide +kernel

/-- Configuration 414 passes the reducibility check. -/
theorem red_cf414 : checkReducible cf414 = true := by decide +kernel

/-- Configuration 415 passes the reducibility check. -/
theorem red_cf415 : checkReducible cf415 = true := by decide +kernel

/-- Configuration 416 passes the reducibility check. -/
theorem red_cf416 : checkReducible cf416 = true := by decide +kernel

/-- Configuration 417 passes the reducibility check. -/
theorem red_cf417 : checkReducible cf417 = true := by decide +kernel

/-- Configuration 418 passes the reducibility check. -/
theorem red_cf418 : checkReducible cf418 = true := by decide +kernel

/-- Configuration 419 passes the reducibility check. -/
theorem red_cf419 : checkReducible cf419 = true := by decide +kernel

/-- Configuration 420 passes the reducibility check. -/
theorem red_cf420 : checkReducible cf420 = true := by decide +kernel

/-- Configuration 421 passes the reducibility check. -/
theorem red_cf421 : checkReducible cf421 = true := by decide +kernel

/-- Configuration 422 passes the reducibility check. -/
theorem red_cf422 : checkReducible cf422 = true := by decide +kernel

/-- Configuration 423 passes the reducibility check. -/
theorem red_cf423 : checkReducible cf423 = true := by decide +kernel

/-- Configuration 424 passes the reducibility check. -/
theorem red_cf424 : checkReducible cf424 = true := by decide +kernel

/-- Configuration 425 passes the reducibility check. -/
theorem red_cf425 : checkReducible cf425 = true := by decide +kernel

/-- Configuration 426 passes the reducibility check. -/
theorem red_cf426 : checkReducible cf426 = true := by decide +kernel

/-- Configuration 427 passes the reducibility check. -/
theorem red_cf427 : checkReducible cf427 = true := by decide +kernel

/-- Configuration 428 passes the reducibility check. -/
theorem red_cf428 : checkReducible cf428 = true := by decide +kernel

/-- Configuration 429 passes the reducibility check. -/
theorem red_cf429 : checkReducible cf429 = true := by decide +kernel

/-- Configuration 430 passes the reducibility check. -/
theorem red_cf430 : checkReducible cf430 = true := by decide +kernel

/-- Configuration 431 passes the reducibility check. -/
theorem red_cf431 : checkReducible cf431 = true := by decide +kernel

/-- Configuration 432 passes the reducibility check. -/
theorem red_cf432 : checkReducible cf432 = true := by decide +kernel

/-- Configuration 433 passes the reducibility check. -/
theorem red_cf433 : checkReducible cf433 = true := by decide +kernel

/-- Configuration 434 passes the reducibility check. -/
theorem red_cf434 : checkReducible cf434 = true := by decide +kernel

/-- Configuration 435 passes the reducibility check. -/
theorem red_cf435 : checkReducible cf435 = true := by decide +kernel

/-- Configuration 436 passes the reducibility check. -/
theorem red_cf436 : checkReducible cf436 = true := by decide +kernel

/-- Configuration 437 passes the reducibility check. -/
theorem red_cf437 : checkReducible cf437 = true := by decide +kernel

/-- Configuration 438 passes the reducibility check. -/
theorem red_cf438 : checkReducible cf438 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 399 to 438 are reducible. -/
theorem red398to438 : ReducibleInRange 398 438 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf399
    | 1 => Or.inr red_cf400
    | 2 => Or.inr red_cf401
    | 3 => Or.inr red_cf402
    | 4 => Or.inr red_cf403
    | 5 => Or.inr red_cf404
    | 6 => Or.inr red_cf405
    | 7 => Or.inr red_cf406
    | 8 => Or.inr red_cf407
    | 9 => Or.inr red_cf408
    | 10 => Or.inr red_cf409
    | 11 => Or.inr red_cf410
    | 12 => Or.inr red_cf411
    | 13 => Or.inr red_cf412
    | 14 => Or.inr red_cf413
    | 15 => Or.inr red_cf414
    | 16 => Or.inr red_cf415
    | 17 => Or.inr red_cf416
    | 18 => Or.inr red_cf417
    | 19 => Or.inr red_cf418
    | 20 => Or.inr red_cf419
    | 21 => Or.inr red_cf420
    | 22 => Or.inr red_cf421
    | 23 => Or.inr red_cf422
    | 24 => Or.inr red_cf423
    | 25 => Or.inr red_cf424
    | 26 => Or.inr red_cf425
    | 27 => Or.inr red_cf426
    | 28 => Or.inr red_cf427
    | 29 => Or.inr red_cf428
    | 30 => Or.inr red_cf429
    | 31 => Or.inr red_cf430
    | 32 => Or.inr red_cf431
    | 33 => Or.inr red_cf432
    | 34 => Or.inr red_cf433
    | 35 => Or.inr red_cf434
    | 36 => Or.inr red_cf435
    | 37 => Or.inr red_cf436
    | 38 => Or.inr red_cf437
    | 39 => Or.inr red_cf438
    | n + 40 => Or.inl (Nat.le_add_left 40 n)

end FourColor
