import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 303 to 306, whose indices in `theConfigs` range over
the segment `[302, 306)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job303to306.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 303 passes the reducibility check. -/
theorem red_cf303 : checkReducible cf303 = true := by decide +kernel

/-- Configuration 304 passes the reducibility check. -/
theorem red_cf304 : checkReducible cf304 = true := by decide +kernel

/-- Configuration 305 passes the reducibility check. -/
theorem red_cf305 : checkReducible cf305 = true := by decide +kernel

/-- Configuration 306 passes the reducibility check. -/
theorem red_cf306 : checkReducible cf306 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 303 to 306 are reducible. -/
theorem red302to306 : ReducibleInRange 302 306 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf303
    | 1 => Or.inr red_cf304
    | 2 => Or.inr red_cf305
    | 3 => Or.inr red_cf306
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
