import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 315 to 318, whose indices in `theConfigs` range over
the segment `[314, 318)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job315to318.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 315 passes the reducibility check. -/
theorem red_cf315 : checkReducible cf315 = true := by decide +kernel

/-- Configuration 316 passes the reducibility check. -/
theorem red_cf316 : checkReducible cf316 = true := by decide +kernel

/-- Configuration 317 passes the reducibility check. -/
theorem red_cf317 : checkReducible cf317 = true := by decide +kernel

/-- Configuration 318 passes the reducibility check. -/
theorem red_cf318 : checkReducible cf318 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 315 to 318 are reducible. -/
theorem red314to318 : ReducibleInRange 314 318 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf315
    | 1 => Or.inr red_cf316
    | 2 => Or.inr red_cf317
    | 3 => Or.inr red_cf318
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
