import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 319 to 322, whose indices in `theConfigs` range over
the segment `[318, 322)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job319to322.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 319 passes the reducibility check. -/
theorem red_cf319 : checkReducible cf319 = true := by decide +kernel

/-- Configuration 320 passes the reducibility check. -/
theorem red_cf320 : checkReducible cf320 = true := by decide +kernel

/-- Configuration 321 passes the reducibility check. -/
theorem red_cf321 : checkReducible cf321 = true := by decide +kernel

/-- Configuration 322 passes the reducibility check. -/
theorem red_cf322 : checkReducible cf322 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 319 to 322 are reducible. -/
theorem red318to322 : ReducibleInRange 318 322 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf319
    | 1 => Or.inr red_cf320
    | 2 => Or.inr red_cf321
    | 3 => Or.inr red_cf322
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
