import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 307 to 310, whose indices in `theConfigs` range over
the segment `[306, 310)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job307to310.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 307 passes the reducibility check. -/
theorem red_cf307 : checkReducible cf307 = true := by decide +kernel

/-- Configuration 308 passes the reducibility check. -/
theorem red_cf308 : checkReducible cf308 = true := by decide +kernel

/-- Configuration 309 passes the reducibility check. -/
theorem red_cf309 : checkReducible cf309 = true := by decide +kernel

/-- Configuration 310 passes the reducibility check. -/
theorem red_cf310 : checkReducible cf310 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 307 to 310 are reducible. -/
theorem red306to310 : ReducibleInRange 306 310 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf307
    | 1 => Or.inr red_cf308
    | 2 => Or.inr red_cf309
    | 3 => Or.inr red_cf310
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
