import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 311 to 314, whose indices in `theConfigs` range over
the segment `[310, 314)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job311to314.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 311 passes the reducibility check. -/
theorem red_cf311 : checkReducible cf311 = true := by decide +kernel

/-- Configuration 312 passes the reducibility check. -/
theorem red_cf312 : checkReducible cf312 = true := by decide +kernel

/-- Configuration 313 passes the reducibility check. -/
theorem red_cf313 : checkReducible cf313 = true := by decide +kernel

/-- Configuration 314 passes the reducibility check. -/
theorem red_cf314 : checkReducible cf314 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 311 to 314 are reducible. -/
theorem red310to314 : ReducibleInRange 310 314 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf311
    | 1 => Or.inr red_cf312
    | 2 => Or.inr red_cf313
    | 3 => Or.inr red_cf314
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
