import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 490 to 494, whose indices in `theConfigs` range over
the segment `[489, 494)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job490to494.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 490 passes the reducibility check. -/
theorem red_cf490 : checkReducible cf490 = true := by decide +kernel

/-- Configuration 491 passes the reducibility check. -/
theorem red_cf491 : checkReducible cf491 = true := by decide +kernel

/-- Configuration 492 passes the reducibility check. -/
theorem red_cf492 : checkReducible cf492 = true := by decide +kernel

/-- Configuration 493 passes the reducibility check. -/
theorem red_cf493 : checkReducible cf493 = true := by decide +kernel

/-- Configuration 494 passes the reducibility check. -/
theorem red_cf494 : checkReducible cf494 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 490 to 494 are reducible. -/
theorem red489to494 : ReducibleInRange 489 494 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf490
    | 1 => Or.inr red_cf491
    | 2 => Or.inr red_cf492
    | 3 => Or.inr red_cf493
    | 4 => Or.inr red_cf494
    | n + 5 => Or.inl (Nat.le_add_left 5 n)

end FourColor
