import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 499 to 502, whose indices in `theConfigs` range over
the segment `[498, 502)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job499to502.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 499 passes the reducibility check. -/
theorem red_cf499 : checkReducible cf499 = true := by decide +kernel

/-- Configuration 500 passes the reducibility check. -/
theorem red_cf500 : checkReducible cf500 = true := by decide +kernel

/-- Configuration 501 passes the reducibility check. -/
theorem red_cf501 : checkReducible cf501 = true := by decide +kernel

/-- Configuration 502 passes the reducibility check. -/
theorem red_cf502 : checkReducible cf502 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 499 to 502 are reducible. -/
theorem red498to502 : ReducibleInRange 498 502 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf499
    | 1 => Or.inr red_cf500
    | 2 => Or.inr red_cf501
    | 3 => Or.inr red_cf502
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
