import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 439 to 465, whose indices in `theConfigs` range over
the segment `[438, 465)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job439to465.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 439 passes the reducibility check. -/
theorem red_cf439 : checkReducible cf439 = true := by decide +kernel

/-- Configuration 440 passes the reducibility check. -/
theorem red_cf440 : checkReducible cf440 = true := by decide +kernel

/-- Configuration 441 passes the reducibility check. -/
theorem red_cf441 : checkReducible cf441 = true := by decide +kernel

/-- Configuration 442 passes the reducibility check. -/
theorem red_cf442 : checkReducible cf442 = true := by decide +kernel

/-- Configuration 443 passes the reducibility check. -/
theorem red_cf443 : checkReducible cf443 = true := by decide +kernel

/-- Configuration 444 passes the reducibility check. -/
theorem red_cf444 : checkReducible cf444 = true := by decide +kernel

/-- Configuration 445 passes the reducibility check. -/
theorem red_cf445 : checkReducible cf445 = true := by decide +kernel

/-- Configuration 446 passes the reducibility check. -/
theorem red_cf446 : checkReducible cf446 = true := by decide +kernel

/-- Configuration 447 passes the reducibility check. -/
theorem red_cf447 : checkReducible cf447 = true := by decide +kernel

/-- Configuration 448 passes the reducibility check. -/
theorem red_cf448 : checkReducible cf448 = true := by decide +kernel

/-- Configuration 449 passes the reducibility check. -/
theorem red_cf449 : checkReducible cf449 = true := by decide +kernel

/-- Configuration 450 passes the reducibility check. -/
theorem red_cf450 : checkReducible cf450 = true := by decide +kernel

/-- Configuration 451 passes the reducibility check. -/
theorem red_cf451 : checkReducible cf451 = true := by decide +kernel

/-- Configuration 452 passes the reducibility check. -/
theorem red_cf452 : checkReducible cf452 = true := by decide +kernel

/-- Configuration 453 passes the reducibility check. -/
theorem red_cf453 : checkReducible cf453 = true := by decide +kernel

/-- Configuration 454 passes the reducibility check. -/
theorem red_cf454 : checkReducible cf454 = true := by decide +kernel

/-- Configuration 455 passes the reducibility check. -/
theorem red_cf455 : checkReducible cf455 = true := by decide +kernel

/-- Configuration 456 passes the reducibility check. -/
theorem red_cf456 : checkReducible cf456 = true := by decide +kernel

/-- Configuration 457 passes the reducibility check. -/
theorem red_cf457 : checkReducible cf457 = true := by decide +kernel

/-- Configuration 458 passes the reducibility check. -/
theorem red_cf458 : checkReducible cf458 = true := by decide +kernel

/-- Configuration 459 passes the reducibility check. -/
theorem red_cf459 : checkReducible cf459 = true := by decide +kernel

/-- Configuration 460 passes the reducibility check. -/
theorem red_cf460 : checkReducible cf460 = true := by decide +kernel

/-- Configuration 461 passes the reducibility check. -/
theorem red_cf461 : checkReducible cf461 = true := by decide +kernel

/-- Configuration 462 passes the reducibility check. -/
theorem red_cf462 : checkReducible cf462 = true := by decide +kernel

/-- Configuration 463 passes the reducibility check. -/
theorem red_cf463 : checkReducible cf463 = true := by decide +kernel

/-- Configuration 464 passes the reducibility check. -/
theorem red_cf464 : checkReducible cf464 = true := by decide +kernel

/-- Configuration 465 passes the reducibility check. -/
theorem red_cf465 : checkReducible cf465 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 439 to 465 are reducible. -/
theorem red438to465 : ReducibleInRange 438 465 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf439
    | 1 => Or.inr red_cf440
    | 2 => Or.inr red_cf441
    | 3 => Or.inr red_cf442
    | 4 => Or.inr red_cf443
    | 5 => Or.inr red_cf444
    | 6 => Or.inr red_cf445
    | 7 => Or.inr red_cf446
    | 8 => Or.inr red_cf447
    | 9 => Or.inr red_cf448
    | 10 => Or.inr red_cf449
    | 11 => Or.inr red_cf450
    | 12 => Or.inr red_cf451
    | 13 => Or.inr red_cf452
    | 14 => Or.inr red_cf453
    | 15 => Or.inr red_cf454
    | 16 => Or.inr red_cf455
    | 17 => Or.inr red_cf456
    | 18 => Or.inr red_cf457
    | 19 => Or.inr red_cf458
    | 20 => Or.inr red_cf459
    | 21 => Or.inr red_cf460
    | 22 => Or.inr red_cf461
    | 23 => Or.inr red_cf462
    | 24 => Or.inr red_cf463
    | 25 => Or.inr red_cf464
    | 26 => Or.inr red_cf465
    | n + 27 => Or.inl (Nat.le_add_left 27 n)

end FourColor
