import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 486 to 489, whose indices in `theConfigs` range over
the segment `[485, 489)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job486to489.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 486 passes the reducibility check. -/
theorem red_cf486 : checkReducible cf486 = true := by decide +kernel

/-- Configuration 487 passes the reducibility check. -/
theorem red_cf487 : checkReducible cf487 = true := by decide +kernel

/-- Configuration 488 passes the reducibility check. -/
theorem red_cf488 : checkReducible cf488 = true := by decide +kernel

/-- Configuration 489 passes the reducibility check. -/
theorem red_cf489 : checkReducible cf489 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 486 to 489 are reducible. -/
theorem red485to489 : ReducibleInRange 485 489 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf486
    | 1 => Or.inr red_cf487
    | 2 => Or.inr red_cf488
    | 3 => Or.inr red_cf489
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
