import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 495 to 498, whose indices in `theConfigs` range over
the segment `[494, 498)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job495to498.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 495 passes the reducibility check. -/
theorem red_cf495 : checkReducible cf495 = true := by decide +kernel

/-- Configuration 496 passes the reducibility check. -/
theorem red_cf496 : checkReducible cf496 = true := by decide +kernel

/-- Configuration 497 passes the reducibility check. -/
theorem red_cf497 : checkReducible cf497 = true := by decide +kernel

/-- Configuration 498 passes the reducibility check. -/
theorem red_cf498 : checkReducible cf498 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 495 to 498 are reducible. -/
theorem red494to498 : ReducibleInRange 494 498 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf495
    | 1 => Or.inr red_cf496
    | 2 => Or.inr red_cf497
    | 3 => Or.inr red_cf498
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
