import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 466 to 485, whose indices in `theConfigs` range over
the segment `[465, 485)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job466to485.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 466 passes the reducibility check. -/
theorem red_cf466 : checkReducible cf466 = true := by decide +kernel

/-- Configuration 467 passes the reducibility check. -/
theorem red_cf467 : checkReducible cf467 = true := by decide +kernel

/-- Configuration 468 passes the reducibility check. -/
theorem red_cf468 : checkReducible cf468 = true := by decide +kernel

/-- Configuration 469 passes the reducibility check. -/
theorem red_cf469 : checkReducible cf469 = true := by decide +kernel

/-- Configuration 470 passes the reducibility check. -/
theorem red_cf470 : checkReducible cf470 = true := by decide +kernel

/-- Configuration 471 passes the reducibility check. -/
theorem red_cf471 : checkReducible cf471 = true := by decide +kernel

/-- Configuration 472 passes the reducibility check. -/
theorem red_cf472 : checkReducible cf472 = true := by decide +kernel

/-- Configuration 473 passes the reducibility check. -/
theorem red_cf473 : checkReducible cf473 = true := by decide +kernel

/-- Configuration 474 passes the reducibility check. -/
theorem red_cf474 : checkReducible cf474 = true := by decide +kernel

/-- Configuration 475 passes the reducibility check. -/
theorem red_cf475 : checkReducible cf475 = true := by decide +kernel

/-- Configuration 476 passes the reducibility check. -/
theorem red_cf476 : checkReducible cf476 = true := by decide +kernel

/-- Configuration 477 passes the reducibility check. -/
theorem red_cf477 : checkReducible cf477 = true := by decide +kernel

/-- Configuration 478 passes the reducibility check. -/
theorem red_cf478 : checkReducible cf478 = true := by decide +kernel

/-- Configuration 479 passes the reducibility check. -/
theorem red_cf479 : checkReducible cf479 = true := by decide +kernel

/-- Configuration 480 passes the reducibility check. -/
theorem red_cf480 : checkReducible cf480 = true := by decide +kernel

/-- Configuration 481 passes the reducibility check. -/
theorem red_cf481 : checkReducible cf481 = true := by decide +kernel

/-- Configuration 482 passes the reducibility check. -/
theorem red_cf482 : checkReducible cf482 = true := by decide +kernel

/-- Configuration 483 passes the reducibility check. -/
theorem red_cf483 : checkReducible cf483 = true := by decide +kernel

/-- Configuration 484 passes the reducibility check. -/
theorem red_cf484 : checkReducible cf484 = true := by decide +kernel

/-- Configuration 485 passes the reducibility check. -/
theorem red_cf485 : checkReducible cf485 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 466 to 485 are reducible. -/
theorem red465to485 : ReducibleInRange 465 485 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf466
    | 1 => Or.inr red_cf467
    | 2 => Or.inr red_cf468
    | 3 => Or.inr red_cf469
    | 4 => Or.inr red_cf470
    | 5 => Or.inr red_cf471
    | 6 => Or.inr red_cf472
    | 7 => Or.inr red_cf473
    | 8 => Or.inr red_cf474
    | 9 => Or.inr red_cf475
    | 10 => Or.inr red_cf476
    | 11 => Or.inr red_cf477
    | 12 => Or.inr red_cf478
    | 13 => Or.inr red_cf479
    | 14 => Or.inr red_cf480
    | 15 => Or.inr red_cf481
    | 16 => Or.inr red_cf482
    | 17 => Or.inr red_cf483
    | 18 => Or.inr red_cf484
    | 19 => Or.inr red_cf485
    | n + 20 => Or.inl (Nat.le_add_left 20 n)

end FourColor
