import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 511 to 516, whose indices in `theConfigs` range over
the segment `[510, 516)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job511to516.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 511 passes the reducibility check. -/
theorem red_cf511 : checkReducible cf511 = true := by decide +kernel

/-- Configuration 512 passes the reducibility check. -/
theorem red_cf512 : checkReducible cf512 = true := by decide +kernel

/-- Configuration 513 passes the reducibility check. -/
theorem red_cf513 : checkReducible cf513 = true := by decide +kernel

/-- Configuration 514 passes the reducibility check. -/
theorem red_cf514 : checkReducible cf514 = true := by decide +kernel

/-- Configuration 515 passes the reducibility check. -/
theorem red_cf515 : checkReducible cf515 = true := by decide +kernel

/-- Configuration 516 passes the reducibility check. -/
theorem red_cf516 : checkReducible cf516 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 511 to 516 are reducible. -/
theorem red510to516 : ReducibleInRange 510 516 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf511
    | 1 => Or.inr red_cf512
    | 2 => Or.inr red_cf513
    | 3 => Or.inr red_cf514
    | 4 => Or.inr red_cf515
    | 5 => Or.inr red_cf516
    | n + 6 => Or.inl (Nat.le_add_left 6 n)

end FourColor
