import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 554 to 562, whose indices in `theConfigs` range over
the segment `[553, 562)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job554to562.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 554 passes the reducibility check. -/
theorem red_cf554 : checkReducible cf554 = true := by decide +kernel

/-- Configuration 555 passes the reducibility check. -/
theorem red_cf555 : checkReducible cf555 = true := by decide +kernel

/-- Configuration 556 passes the reducibility check. -/
theorem red_cf556 : checkReducible cf556 = true := by decide +kernel

/-- Configuration 557 passes the reducibility check. -/
theorem red_cf557 : checkReducible cf557 = true := by decide +kernel

/-- Configuration 558 passes the reducibility check. -/
theorem red_cf558 : checkReducible cf558 = true := by decide +kernel

/-- Configuration 559 passes the reducibility check. -/
theorem red_cf559 : checkReducible cf559 = true := by decide +kernel

/-- Configuration 560 passes the reducibility check. -/
theorem red_cf560 : checkReducible cf560 = true := by decide +kernel

/-- Configuration 561 passes the reducibility check. -/
theorem red_cf561 : checkReducible cf561 = true := by decide +kernel

/-- Configuration 562 passes the reducibility check. -/
theorem red_cf562 : checkReducible cf562 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 554 to 562 are reducible. -/
theorem red553to562 : ReducibleInRange 553 562 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf554
    | 1 => Or.inr red_cf555
    | 2 => Or.inr red_cf556
    | 3 => Or.inr red_cf557
    | 4 => Or.inr red_cf558
    | 5 => Or.inr red_cf559
    | 6 => Or.inr red_cf560
    | 7 => Or.inr red_cf561
    | 8 => Or.inr red_cf562
    | n + 9 => Or.inl (Nat.le_add_left 9 n)

end FourColor
