import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 550 to 553, whose indices in `theConfigs` range over
the segment `[549, 553)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job550to553.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 550 passes the reducibility check. -/
theorem red_cf550 : checkReducible cf550 = true := by decide +kernel

/-- Configuration 551 passes the reducibility check. -/
theorem red_cf551 : checkReducible cf551 = true := by decide +kernel

/-- Configuration 552 passes the reducibility check. -/
theorem red_cf552 : checkReducible cf552 = true := by decide +kernel

/-- Configuration 553 passes the reducibility check. -/
theorem red_cf553 : checkReducible cf553 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 550 to 553 are reducible. -/
theorem red549to553 : ReducibleInRange 549 553 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf550
    | 1 => Or.inr red_cf551
    | 2 => Or.inr red_cf552
    | 3 => Or.inr red_cf553
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
