import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 507 to 510, whose indices in `theConfigs` range over
the segment `[506, 510)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job507to510.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 507 passes the reducibility check. -/
theorem red_cf507 : checkReducible cf507 = true := by decide +kernel

/-- Configuration 508 passes the reducibility check. -/
theorem red_cf508 : checkReducible cf508 = true := by decide +kernel

/-- Configuration 509 passes the reducibility check. -/
theorem red_cf509 : checkReducible cf509 = true := by decide +kernel

/-- Configuration 510 passes the reducibility check. -/
theorem red_cf510 : checkReducible cf510 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 507 to 510 are reducible. -/
theorem red506to510 : ReducibleInRange 506 510 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf507
    | 1 => Or.inr red_cf508
    | 2 => Or.inr red_cf509
    | 3 => Or.inr red_cf510
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
