import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 517 to 530, whose indices in `theConfigs` range over
the segment `[516, 530)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job517to530.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 517 passes the reducibility check. -/
theorem red_cf517 : checkReducible cf517 = true := by decide +kernel

/-- Configuration 518 passes the reducibility check. -/
theorem red_cf518 : checkReducible cf518 = true := by decide +kernel

/-- Configuration 519 passes the reducibility check. -/
theorem red_cf519 : checkReducible cf519 = true := by decide +kernel

/-- Configuration 520 passes the reducibility check. -/
theorem red_cf520 : checkReducible cf520 = true := by decide +kernel

/-- Configuration 521 passes the reducibility check. -/
theorem red_cf521 : checkReducible cf521 = true := by decide +kernel

/-- Configuration 522 passes the reducibility check. -/
theorem red_cf522 : checkReducible cf522 = true := by decide +kernel

/-- Configuration 523 passes the reducibility check. -/
theorem red_cf523 : checkReducible cf523 = true := by decide +kernel

/-- Configuration 524 passes the reducibility check. -/
theorem red_cf524 : checkReducible cf524 = true := by decide +kernel

/-- Configuration 525 passes the reducibility check. -/
theorem red_cf525 : checkReducible cf525 = true := by decide +kernel

/-- Configuration 526 passes the reducibility check. -/
theorem red_cf526 : checkReducible cf526 = true := by decide +kernel

/-- Configuration 527 passes the reducibility check. -/
theorem red_cf527 : checkReducible cf527 = true := by decide +kernel

/-- Configuration 528 passes the reducibility check. -/
theorem red_cf528 : checkReducible cf528 = true := by decide +kernel

/-- Configuration 529 passes the reducibility check. -/
theorem red_cf529 : checkReducible cf529 = true := by decide +kernel

/-- Configuration 530 passes the reducibility check. -/
theorem red_cf530 : checkReducible cf530 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 517 to 530 are reducible. -/
theorem red516to530 : ReducibleInRange 516 530 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf517
    | 1 => Or.inr red_cf518
    | 2 => Or.inr red_cf519
    | 3 => Or.inr red_cf520
    | 4 => Or.inr red_cf521
    | 5 => Or.inr red_cf522
    | 6 => Or.inr red_cf523
    | 7 => Or.inr red_cf524
    | 8 => Or.inr red_cf525
    | 9 => Or.inr red_cf526
    | 10 => Or.inr red_cf527
    | 11 => Or.inr red_cf528
    | 12 => Or.inr red_cf529
    | 13 => Or.inr red_cf530
    | n + 14 => Or.inl (Nat.le_add_left 14 n)

end FourColor
