import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 531 to 534, whose indices in `theConfigs` range over
the segment `[530, 534)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job531to534.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 531 passes the reducibility check. -/
theorem red_cf531 : checkReducible cf531 = true := by decide +kernel

/-- Configuration 532 passes the reducibility check. -/
theorem red_cf532 : checkReducible cf532 = true := by decide +kernel

/-- Configuration 533 passes the reducibility check. -/
theorem red_cf533 : checkReducible cf533 = true := by decide +kernel

/-- Configuration 534 passes the reducibility check. -/
theorem red_cf534 : checkReducible cf534 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 531 to 534 are reducible. -/
theorem red530to534 : ReducibleInRange 530 534 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf531
    | 1 => Or.inr red_cf532
    | 2 => Or.inr red_cf533
    | 3 => Or.inr red_cf534
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
