import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 563 to 588, whose indices in `theConfigs` range over
the segment `[562, 588)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job563to588.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 563 passes the reducibility check. -/
theorem red_cf563 : checkReducible cf563 = true := by decide +kernel

/-- Configuration 564 passes the reducibility check. -/
theorem red_cf564 : checkReducible cf564 = true := by decide +kernel

/-- Configuration 565 passes the reducibility check. -/
theorem red_cf565 : checkReducible cf565 = true := by decide +kernel

/-- Configuration 566 passes the reducibility check. -/
theorem red_cf566 : checkReducible cf566 = true := by decide +kernel

/-- Configuration 567 passes the reducibility check. -/
theorem red_cf567 : checkReducible cf567 = true := by decide +kernel

/-- Configuration 568 passes the reducibility check. -/
theorem red_cf568 : checkReducible cf568 = true := by decide +kernel

/-- Configuration 569 passes the reducibility check. -/
theorem red_cf569 : checkReducible cf569 = true := by decide +kernel

/-- Configuration 570 passes the reducibility check. -/
theorem red_cf570 : checkReducible cf570 = true := by decide +kernel

/-- Configuration 571 passes the reducibility check. -/
theorem red_cf571 : checkReducible cf571 = true := by decide +kernel

/-- Configuration 572 passes the reducibility check. -/
theorem red_cf572 : checkReducible cf572 = true := by decide +kernel

/-- Configuration 573 passes the reducibility check. -/
theorem red_cf573 : checkReducible cf573 = true := by decide +kernel

/-- Configuration 574 passes the reducibility check. -/
theorem red_cf574 : checkReducible cf574 = true := by decide +kernel

/-- Configuration 575 passes the reducibility check. -/
theorem red_cf575 : checkReducible cf575 = true := by decide +kernel

/-- Configuration 576 passes the reducibility check. -/
theorem red_cf576 : checkReducible cf576 = true := by decide +kernel

/-- Configuration 577 passes the reducibility check. -/
theorem red_cf577 : checkReducible cf577 = true := by decide +kernel

/-- Configuration 578 passes the reducibility check. -/
theorem red_cf578 : checkReducible cf578 = true := by decide +kernel

/-- Configuration 579 passes the reducibility check. -/
theorem red_cf579 : checkReducible cf579 = true := by decide +kernel

/-- Configuration 580 passes the reducibility check. -/
theorem red_cf580 : checkReducible cf580 = true := by decide +kernel

/-- Configuration 581 passes the reducibility check. -/
theorem red_cf581 : checkReducible cf581 = true := by decide +kernel

/-- Configuration 582 passes the reducibility check. -/
theorem red_cf582 : checkReducible cf582 = true := by decide +kernel

/-- Configuration 583 passes the reducibility check. -/
theorem red_cf583 : checkReducible cf583 = true := by decide +kernel

/-- Configuration 584 passes the reducibility check. -/
theorem red_cf584 : checkReducible cf584 = true := by decide +kernel

/-- Configuration 585 passes the reducibility check. -/
theorem red_cf585 : checkReducible cf585 = true := by decide +kernel

/-- Configuration 586 passes the reducibility check. -/
theorem red_cf586 : checkReducible cf586 = true := by decide +kernel

/-- Configuration 587 passes the reducibility check. -/
theorem red_cf587 : checkReducible cf587 = true := by decide +kernel

/-- Configuration 588 passes the reducibility check. -/
theorem red_cf588 : checkReducible cf588 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 563 to 588 are reducible. -/
theorem red562to588 : ReducibleInRange 562 588 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf563
    | 1 => Or.inr red_cf564
    | 2 => Or.inr red_cf565
    | 3 => Or.inr red_cf566
    | 4 => Or.inr red_cf567
    | 5 => Or.inr red_cf568
    | 6 => Or.inr red_cf569
    | 7 => Or.inr red_cf570
    | 8 => Or.inr red_cf571
    | 9 => Or.inr red_cf572
    | 10 => Or.inr red_cf573
    | 11 => Or.inr red_cf574
    | 12 => Or.inr red_cf575
    | 13 => Or.inr red_cf576
    | 14 => Or.inr red_cf577
    | 15 => Or.inr red_cf578
    | 16 => Or.inr red_cf579
    | 17 => Or.inr red_cf580
    | 18 => Or.inr red_cf581
    | 19 => Or.inr red_cf582
    | 20 => Or.inr red_cf583
    | 21 => Or.inr red_cf584
    | 22 => Or.inr red_cf585
    | 23 => Or.inr red_cf586
    | 24 => Or.inr red_cf587
    | 25 => Or.inr red_cf588
    | n + 26 => Or.inl (Nat.le_add_left 26 n)

end FourColor
