import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 535 to 541, whose indices in `theConfigs` range over
the segment `[534, 541)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job535to541.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 535 passes the reducibility check. -/
theorem red_cf535 : checkReducible cf535 = true := by decide +kernel

/-- Configuration 536 passes the reducibility check. -/
theorem red_cf536 : checkReducible cf536 = true := by decide +kernel

/-- Configuration 537 passes the reducibility check. -/
theorem red_cf537 : checkReducible cf537 = true := by decide +kernel

/-- Configuration 538 passes the reducibility check. -/
theorem red_cf538 : checkReducible cf538 = true := by decide +kernel

/-- Configuration 539 passes the reducibility check. -/
theorem red_cf539 : checkReducible cf539 = true := by decide +kernel

/-- Configuration 540 passes the reducibility check. -/
theorem red_cf540 : checkReducible cf540 = true := by decide +kernel

/-- Configuration 541 passes the reducibility check. -/
theorem red_cf541 : checkReducible cf541 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 535 to 541 are reducible. -/
theorem red534to541 : ReducibleInRange 534 541 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf535
    | 1 => Or.inr red_cf536
    | 2 => Or.inr red_cf537
    | 3 => Or.inr red_cf538
    | 4 => Or.inr red_cf539
    | 5 => Or.inr red_cf540
    | 6 => Or.inr red_cf541
    | n + 7 => Or.inl (Nat.le_add_left 7 n)

end FourColor
