import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 546 to 549, whose indices in `theConfigs` range over
the segment `[545, 549)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job546to549.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 546 passes the reducibility check. -/
theorem red_cf546 : checkReducible cf546 = true := by decide +kernel

/-- Configuration 547 passes the reducibility check. -/
theorem red_cf547 : checkReducible cf547 = true := by decide +kernel

/-- Configuration 548 passes the reducibility check. -/
theorem red_cf548 : checkReducible cf548 = true := by decide +kernel

/-- Configuration 549 passes the reducibility check. -/
theorem red_cf549 : checkReducible cf549 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 546 to 549 are reducible. -/
theorem red545to549 : ReducibleInRange 545 549 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf546
    | 1 => Or.inr red_cf547
    | 2 => Or.inr red_cf548
    | 3 => Or.inr red_cf549
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
