import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 503 to 506, whose indices in `theConfigs` range over
the segment `[502, 506)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job503to506.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 503 passes the reducibility check. -/
theorem red_cf503 : checkReducible cf503 = true := by decide +kernel

/-- Configuration 504 passes the reducibility check. -/
theorem red_cf504 : checkReducible cf504 = true := by decide +kernel

/-- Configuration 505 passes the reducibility check. -/
theorem red_cf505 : checkReducible cf505 = true := by decide +kernel

/-- Configuration 506 passes the reducibility check. -/
theorem red_cf506 : checkReducible cf506 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 503 to 506 are reducible. -/
theorem red502to506 : ReducibleInRange 502 506 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf503
    | 1 => Or.inr red_cf504
    | 2 => Or.inr red_cf505
    | 3 => Or.inr red_cf506
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
