import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 542 to 545, whose indices in `theConfigs` range over
the segment `[541, 545)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job542to545.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 542 passes the reducibility check. -/
theorem red_cf542 : checkReducible cf542 = true := by decide +kernel

/-- Configuration 543 passes the reducibility check. -/
theorem red_cf543 : checkReducible cf543 = true := by decide +kernel

/-- Configuration 544 passes the reducibility check. -/
theorem red_cf544 : checkReducible cf544 = true := by decide +kernel

/-- Configuration 545 passes the reducibility check. -/
theorem red_cf545 : checkReducible cf545 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 542 to 545 are reducible. -/
theorem red541to545 : ReducibleInRange 541 545 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf542
    | 1 => Or.inr red_cf543
    | 2 => Or.inr red_cf544
    | 3 => Or.inr red_cf545
    | n + 4 => Or.inl (Nat.le_add_left 4 n)

end FourColor
