import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 589 to 610, whose indices in `theConfigs` range over
the segment `[588, 610)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job589to610.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 589 passes the reducibility check. -/
theorem red_cf589 : checkReducible cf589 = true := by decide +kernel

/-- Configuration 590 passes the reducibility check. -/
theorem red_cf590 : checkReducible cf590 = true := by decide +kernel

/-- Configuration 591 passes the reducibility check. -/
theorem red_cf591 : checkReducible cf591 = true := by decide +kernel

/-- Configuration 592 passes the reducibility check. -/
theorem red_cf592 : checkReducible cf592 = true := by decide +kernel

/-- Configuration 593 passes the reducibility check. -/
theorem red_cf593 : checkReducible cf593 = true := by decide +kernel

/-- Configuration 594 passes the reducibility check. -/
theorem red_cf594 : checkReducible cf594 = true := by decide +kernel

/-- Configuration 595 passes the reducibility check. -/
theorem red_cf595 : checkReducible cf595 = true := by decide +kernel

/-- Configuration 596 passes the reducibility check. -/
theorem red_cf596 : checkReducible cf596 = true := by decide +kernel

/-- Configuration 597 passes the reducibility check. -/
theorem red_cf597 : checkReducible cf597 = true := by decide +kernel

/-- Configuration 598 passes the reducibility check. -/
theorem red_cf598 : checkReducible cf598 = true := by decide +kernel

/-- Configuration 599 passes the reducibility check. -/
theorem red_cf599 : checkReducible cf599 = true := by decide +kernel

/-- Configuration 600 passes the reducibility check. -/
theorem red_cf600 : checkReducible cf600 = true := by decide +kernel

/-- Configuration 601 passes the reducibility check. -/
theorem red_cf601 : checkReducible cf601 = true := by decide +kernel

/-- Configuration 602 passes the reducibility check. -/
theorem red_cf602 : checkReducible cf602 = true := by decide +kernel

/-- Configuration 603 passes the reducibility check. -/
theorem red_cf603 : checkReducible cf603 = true := by decide +kernel

/-- Configuration 604 passes the reducibility check. -/
theorem red_cf604 : checkReducible cf604 = true := by decide +kernel

/-- Configuration 605 passes the reducibility check. -/
theorem red_cf605 : checkReducible cf605 = true := by decide +kernel

/-- Configuration 606 passes the reducibility check. -/
theorem red_cf606 : checkReducible cf606 = true := by decide +kernel

/-- Configuration 607 passes the reducibility check. -/
theorem red_cf607 : checkReducible cf607 = true := by decide +kernel

/-- Configuration 608 passes the reducibility check. -/
theorem red_cf608 : checkReducible cf608 = true := by decide +kernel

/-- Configuration 609 passes the reducibility check. -/
theorem red_cf609 : checkReducible cf609 = true := by decide +kernel

/-- Configuration 610 passes the reducibility check. -/
theorem red_cf610 : checkReducible cf610 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 589 to 610 are reducible. -/
theorem red588to610 : ReducibleInRange 588 610 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf589
    | 1 => Or.inr red_cf590
    | 2 => Or.inr red_cf591
    | 3 => Or.inr red_cf592
    | 4 => Or.inr red_cf593
    | 5 => Or.inr red_cf594
    | 6 => Or.inr red_cf595
    | 7 => Or.inr red_cf596
    | 8 => Or.inr red_cf597
    | 9 => Or.inr red_cf598
    | 10 => Or.inr red_cf599
    | 11 => Or.inr red_cf600
    | 12 => Or.inr red_cf601
    | 13 => Or.inr red_cf602
    | 14 => Or.inr red_cf603
    | 15 => Or.inr red_cf604
    | 16 => Or.inr red_cf605
    | 17 => Or.inr red_cf606
    | 18 => Or.inr red_cf607
    | 19 => Or.inr red_cf608
    | 20 => Or.inr red_cf609
    | 21 => Or.inr red_cf610
    | n + 22 => Or.inl (Nat.le_add_left 22 n)

end FourColor
