import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 623 to 633, whose indices in `theConfigs` range over
the segment `[622, 633)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job623to633.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 623 passes the reducibility check. -/
theorem red_cf623 : checkReducible cf623 = true := by decide +kernel

/-- Configuration 624 passes the reducibility check. -/
theorem red_cf624 : checkReducible cf624 = true := by decide +kernel

/-- Configuration 625 passes the reducibility check. -/
theorem red_cf625 : checkReducible cf625 = true := by decide +kernel

/-- Configuration 626 passes the reducibility check. -/
theorem red_cf626 : checkReducible cf626 = true := by decide +kernel

/-- Configuration 627 passes the reducibility check. -/
theorem red_cf627 : checkReducible cf627 = true := by decide +kernel

/-- Configuration 628 passes the reducibility check. -/
theorem red_cf628 : checkReducible cf628 = true := by decide +kernel

/-- Configuration 629 passes the reducibility check. -/
theorem red_cf629 : checkReducible cf629 = true := by decide +kernel

/-- Configuration 630 passes the reducibility check. -/
theorem red_cf630 : checkReducible cf630 = true := by decide +kernel

/-- Configuration 631 passes the reducibility check. -/
theorem red_cf631 : checkReducible cf631 = true := by decide +kernel

/-- Configuration 632 passes the reducibility check. -/
theorem red_cf632 : checkReducible cf632 = true := by decide +kernel

/-- Configuration 633 passes the reducibility check. -/
theorem red_cf633 : checkReducible cf633 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 623 to 633 are reducible. -/
theorem red622to633 : ReducibleInRange 622 633 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf623
    | 1 => Or.inr red_cf624
    | 2 => Or.inr red_cf625
    | 3 => Or.inr red_cf626
    | 4 => Or.inr red_cf627
    | 5 => Or.inr red_cf628
    | 6 => Or.inr red_cf629
    | 7 => Or.inr red_cf630
    | 8 => Or.inr red_cf631
    | 9 => Or.inr red_cf632
    | 10 => Or.inr red_cf633
    | n + 11 => Or.inl (Nat.le_add_left 11 n)

end FourColor
