import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 611 to 617, whose indices in `theConfigs` range over
the segment `[610, 617)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job611to617.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 611 passes the reducibility check. -/
theorem red_cf611 : checkReducible cf611 = true := by decide +kernel

/-- Configuration 612 passes the reducibility check. -/
theorem red_cf612 : checkReducible cf612 = true := by decide +kernel

/-- Configuration 613 passes the reducibility check. -/
theorem red_cf613 : checkReducible cf613 = true := by decide +kernel

/-- Configuration 614 passes the reducibility check. -/
theorem red_cf614 : checkReducible cf614 = true := by decide +kernel

/-- Configuration 615 passes the reducibility check. -/
theorem red_cf615 : checkReducible cf615 = true := by decide +kernel

/-- Configuration 616 passes the reducibility check. -/
theorem red_cf616 : checkReducible cf616 = true := by decide +kernel

/-- Configuration 617 passes the reducibility check. -/
theorem red_cf617 : checkReducible cf617 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 611 to 617 are reducible. -/
theorem red610to617 : ReducibleInRange 610 617 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf611
    | 1 => Or.inr red_cf612
    | 2 => Or.inr red_cf613
    | 3 => Or.inr red_cf614
    | 4 => Or.inr red_cf615
    | 5 => Or.inr red_cf616
    | 6 => Or.inr red_cf617
    | n + 7 => Or.inl (Nat.le_add_left 7 n)

end FourColor
