import FourColor.CfReducible
import FourColor.Configurations

/-!
Reducibility of configurations 618 to 622, whose indices in `theConfigs` range over
the segment `[617, 622)`.  Generated by `scripts/gen_reducible.py` after the reference's
`job618to622.v`: one theorem per configuration evaluating `checkReducible`, then the
range lemma assembled from them as the reference's `CheckReducible` tactic does.
-/

namespace FourColor

/-- Configuration 618 passes the reducibility check. -/
theorem red_cf618 : checkReducible cf618 = true := by decide +kernel

/-- Configuration 619 passes the reducibility check. -/
theorem red_cf619 : checkReducible cf619 = true := by decide +kernel

/-- Configuration 620 passes the reducibility check. -/
theorem red_cf620 : checkReducible cf620 = true := by decide +kernel

/-- Configuration 621 passes the reducibility check. -/
theorem red_cf621 : checkReducible cf621 = true := by decide +kernel

/-- Configuration 622 passes the reducibility check. -/
theorem red_cf622 : checkReducible cf622 = true := by decide +kernel

set_option maxRecDepth 8192 in
/-- Configurations 618 to 622 are reducible. -/
theorem red617to622 : ReducibleInRange 617 622 theConfigs :=
  check_reducible_in_range fun i =>
    match i with
    | 0 => Or.inr red_cf618
    | 1 => Or.inr red_cf619
    | 2 => Or.inr red_cf620
    | 3 => Or.inr red_cf621
    | 4 => Or.inr red_cf622
    | n + 5 => Or.inl (Nat.le_add_left 5 n)

end FourColor
