#!/usr/bin/env python3
"""Generate FourColor/Reducible/*.lean: the reducibility job files, the task files that
chain them, and All.lean, mirroring the partition of the Coq proof
(theories/proof/job001to106.v ... job623to633.v, task001to214.v ... task589to633.v,
reducibility.v).  Configuration number n has index n - 1 in theConfigs."""
import os, sys
JOBS = [(1,106),(107,164),(165,189),(190,206),(207,214),(215,218),(219,222),(223,226),(227,230),
        (231,234),(235,238),(239,253),(254,270),(271,278),(279,282),(283,286),(287,290),(291,294),
        (295,298),(299,302),(303,306),(307,310),(311,314),(315,318),(319,322),(323,383),(384,398),
        (399,438),(439,465),(466,485),(486,489),(490,494),(495,498),(499,502),(503,506),(507,510),
        (511,516),(517,530),(531,534),(535,541),(542,545),(546,549),(550,553),(554,562),(563,588),
        (589,610),(611,617),(618,622),(623,633)]
TASKS = [(1,214),(215,234),(235,282),(283,302),(303,322),(323,485),(486,506),(507,541),(542,588),(589,633)]
assert JOBS[0][0] == 1 and JOBS[-1][1] == 633
for (a,b),(c,d) in zip(JOBS, JOBS[1:]): assert c == b + 1
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'FourColor', 'Reducible')
os.makedirs(out, exist_ok=True)
def red(lo, hi): return f"red{lo-1:03d}to{hi:03d}"          # Coq's name: 0-based lower bound
def jobmod(lo, hi): return f"Job{lo:03d}to{hi:03d}"
def taskmod(lo, hi): return f"Task{lo:03d}to{hi:03d}"
for lo, hi in JOBS:
    n = hi - lo + 1
    L = [f"import FourColor.CfReducible", "import FourColor.Configurations", "",
         f"/-!\nReducibility of configurations {lo} to {hi}, whose indices in `theConfigs` range over\n"
         f"the segment `[{lo-1}, {hi})`.  Generated by `scripts/gen_reducible.py` after the reference's\n"
         f"`job{lo:03d}to{hi:03d}.v`: one theorem per configuration evaluating `checkReducible`, then the\n"
         f"range lemma assembled from them as the reference's `CheckReducible` tactic does.\n-/", "",
         "namespace FourColor", ""]
    for k in range(lo, hi + 1):
        L += [f"/-- Configuration {k} passes the reducibility check. -/",
              f"theorem red_cf{k:03d} : checkReducible cf{k:03d} = true := by decide +kernel", ""]
    # the elaborator reduces `((theConfigs.drop j).take n)[i]!` to the configuration by whnf,
    # one recursion level per list cell dropped; the default depth of 512 is not enough past
    # configuration 512
    L += [f"set_option maxRecDepth 8192 in",
          f"/-- Configurations {lo} to {hi} are reducible. -/",
          f"theorem {red(lo,hi)} : ReducibleInRange {lo-1} {hi} theConfigs :=",
          f"  check_reducible_in_range fun i =>",
          f"    match i with"]
    for m, k in enumerate(range(lo, hi + 1)):
        L.append(f"    | {m} => Or.inr red_cf{k:03d}")
    L.append(f"    | n + {n} => Or.inl (Nat.le_add_left {n} n)")
    L += ["", "end FourColor", ""]
    open(os.path.join(out, jobmod(lo,hi) + ".lean"), "w").write("\n".join(L))
def chain(name, lo, hi, parts, header):
    L = [f"import FourColor.Reducible.{p}" for p in parts] + ["", header, "", "namespace FourColor", ""]
    names = [red(a,b) for a,b in parts_ranges]
    # nested left to right, one range per line:  cat (cat (cat a b) c) d
    lines = [f"  {names[0]}"]
    for nm in names[1:]:
        lines = ["  (cat_reducible_range"] + ["  " + l for l in lines] + [f"    {nm})"]
    L += [f"/-- Configurations {lo} to {hi} are reducible. -/",
          f"theorem {red(lo,hi)} : ReducibleInRange {lo-1} {hi} theConfigs :="] + lines + ["", "end FourColor", ""]
    open(os.path.join(out, name + ".lean"), "w").write("\n".join(L))
for lo, hi in TASKS:
    parts_ranges = [(a,b) for a,b in JOBS if lo <= a and b <= hi]
    assert parts_ranges[0][0] == lo and parts_ranges[-1][1] == hi
    chain(taskmod(lo,hi), lo, hi, [jobmod(a,b) for a,b in parts_ranges],
          f"/-!\nReducibility of configurations {lo} to {hi}: the reference's `task{lo:03d}to{hi:03d}.v`,\n"
          f"chaining the job files with `cat_reducible_range` as its `CatReducible` tactic does.\n-/")
parts_ranges = TASKS
chain("All", 1, 633, [taskmod(a,b) for a,b in TASKS],
      "/-!\nEvery configuration is reducible: the reference's `reducibility.v`.\n-/")
# All.lean states reducible_all under the Coq name red000to633 as well
p = os.path.join(out, "All.lean"); s = open(p).read()
s = s.replace("end FourColor", "/-- Every one of the 633 configurations is reducible: the hypothesis `Complete.lean`\nconsumes. -/\ntheorem reducible_all : ReducibleInRange 0 633 theConfigs := red000to633\n\nend FourColor")
open(p, "w").write(s)
print("generated", len(JOBS), "jobs,", len(TASKS), "tasks")
